/**
 * 翻译字典模块
 * 
 * safeGlobalDict:  安全长句字典，不会与代码变量冲突，可直接全局替换
 * riskyShortWords: 危险短词字典，只能在 UI 属性上下文中替换，否则会导致白屏
 */

const safeGlobalDict = {
    "Always Local Singleton": "始终本地单例",
    "Conversation Search": "对话搜索",
    "Manage Account": "管理账号",
    "Manage your account and billing": "管理您的账号与账单",
    "Invite Team Members": "邀请团队成员",
    "Accelerate development, shared knowledge, and context across your team": "跨团队加速开发并共享知识与上下文",
    "Preferences": "偏好设置",
    "Back": "返回",
    "Cursor Account": "Cursor 账号",
    "Warning Notifications": "警告通知",
    "Show warning-level in-app toasts": "显示警告级别的应用内提示",
    "Menu Bar Icon": "菜单栏图标",
    "Show Cursor in menu bar": "在菜单栏显示 Cursor",
    "Worktrees": "工作树",
    "Cleanup": "清理",
    "Cursor periodically removes old worktrees to free disk space. Tune how aggressively cleanup runs.": "Cursor 会定期移除旧工作树以释放磁盘空间。可调整清理执行的积极程度。",
    "Max worktrees": "最大工作树数量",
    "Maximum number of Cursor-managed worktrees to retain across all workspaces. Older worktrees are removed first.": "在所有工作区中保留的 Cursor 托管工作树最大数量。较旧的工作树会优先移除。",
    "Max total size (GB)": "最大总大小（GB）",
    "Maximum total size in GB across all Cursor-managed worktrees. Set to 0 to disable the size limit.": "所有 Cursor 托管工作树的最大总大小（GB）。设置为 0 可禁用大小限制。",
    "Cursor-managed worktrees": "Cursor 托管的工作树",
    "No Cursor-managed worktrees on this machine.": "此设备上没有 Cursor 托管的工作树。",
    "Sync layouts across windows": "跨窗口同步布局",
    "When enabled, all windows share the same layout": "启用后，所有窗口共享相同的布局",
    "Choose between light, dark, or high contrast themes": "在浅色、深色或高对比度主题之间选择",
    "Choose a tint color": "选择一种强调色",
    "Control how strongly the tint is applied": "控制强调色应用的强度",
    "Reduce Transparency": "降低透明度",
    "Replace translucent surfaces with opaque backgrounds": "使用不透明背景替换半透明界面",
    "Compact Terminal Tool Calls": "紧凑显示终端工具调用",
    "Show terminal commands in compact view by default": "默认以紧凑视图显示终端命令",
    "UI Font Size": "界面字体大小",
    "Font size for the Cursor user interface": "Cursor 用户界面的字体大小",
    "Code Font Size": "代码字体大小",
    "Font size for code editors and diffs": "代码编辑器和差异视图的字体大小",
    "UI Font Family": "界面字体",
    "Override the Cursor user interface typeface": "覆盖 Cursor 用户界面的字体",
    "Code Font Family": "代码字体",
    "Override the font for code editors and diffs": "覆盖代码编辑器和差异视图的字体",
    "System font": "系统字体",
    "System monospace": "系统等宽字体",
    "Font Smoothing": "字体平滑",
    "Use native macOS font anti-aliasing": "使用 macOS 原生字体抗锯齿",
    "Hide Email Address": "隐藏邮箱地址",
    "Partially mask your email address in the Cursor user interface": "在 Cursor 用户界面中部分遮盖您的邮箱地址",
    "Editor Settings": "编辑器设置",
    "Configure font, formatting, minimap and more": "配置字体、格式化、缩略图等",
    "Keyboard Shortcuts": "键盘快捷键",
    "Configure keyboard shortcuts": "配置键盘快捷键",
    "Import Settings from VS Code": "从 VS Code 导入设置",
    "Import settings, extensions, and keybindings from VS Code": "导入 VS Code 的设置、扩展和快捷键绑定",
    "See warnings and tips that you've hidden": "查看您已隐藏的警告和提示",
    "Layout": "布局",
    "Status Bar": "状态栏",
    "Show status bar": "显示状态栏",
    "Auto-hide editor when empty": "空闲时自动隐藏编辑器",
    "Auto-Hide Editor When Empty": "编辑器为空时自动隐藏",
    "When all editors are closed, hide the editor area and maximize chat": "关闭所有编辑器时，隐藏编辑器并最大化聊天窗口",
    "Open Chat as Editor Tabs": "将聊天作为编辑器标签页打开",
    "Show chats as editor tabs inside the chat area instead of the legacy stacked view": "在聊天区域中以编辑器标签页显示聊天，而非旧版堆叠视图",
    "Startup": "启动",
    "Window Restoration": "窗口恢复",
    "Controls which windows Cursor restores on startup": "控制 Cursor 启动时恢复哪些窗口",
    "Notifications": "通知",
    "System Notifications": "系统通知",
    "Show system notifications when Agent completes or needs attention": "智能体完成任务或需要注意时显示系统通知",
    "System Tray Icon": "系统托盘图标",
    "Show Cursor in system tray": "在系统托盘显示 Cursor",
    "Completion Sound": "完成提示音",
    "Play a sound when Agent finishes responding": "智能体完成响应时播放提示音",
    "Privacy": "隐私",
    "Rules, Skills, Subagents": "规则、技能与子智能体",
    "Tools & MCP": "工具与 MCP",
    "Tools & MCPs": "工具与 MCP",
    "Git & PRs": "Git 与 PR",
    "Browser & Network": "浏览器与网络",
    "Indexing & Docs": "索引与文档",
    "Cloud Agents": "云端智能体",
    "Profile": "个人资料",
    "Fun": "趣味",
    "Customize": "自定义",
    "Self-driving PRs": "自动 PR",
    "Developer": "开发者",
    "Team Plan": "团队版",
    "Plugins": "插件",
    "Search settings": "搜索设置",
    "Search Settings": "搜索设置",
    "VS Code Settings": "VS Code 设置",
    "Open VS Code Settings": "打开 VS Code 设置",
    "Plan & Usage": "套餐与用量",
    "Manage View": "管理视图",
    "Current Plan": "当前套餐",
    "Ultra Plan": "Ultra 套餐",
    "Pro+ Plan": "Pro+ 套餐",
    "Pro Plan": "Pro 套餐",
    "Free Plan": "免费套餐",
    "Pro+ Trial": "Pro+ 试用",
    "Pro Trial": "Pro 试用",

    // ── API Keys / Provider keys ──
    "API Keys": "API 密钥",
    "OpenAI API Key": "OpenAI API 密钥",
    "You can put in your OpenAI key to use OpenAI models at cost.": "你可以填写你的 OpenAI 密钥，以按成本使用 OpenAI 模型。",
    "You can put in": "你可以填写",
    "You can put in ": "你可以填写 ",
    "your OpenAI key": "你的 OpenAI 密钥",
    "to use OpenAI models at cost.": "以按成本使用 OpenAI 模型。",
    " to use OpenAI models at cost.": "，以按成本使用 OpenAI 模型。",
    "Enter your OpenAI API Key": "请输入 OpenAI API 密钥",
    "Override OpenAI Base URL": "覆盖 OpenAI 基础 URL",
    "Change the base URL for OpenAI API requests.": "修改 OpenAI API 请求的基础 URL。",
    "Anthropic API Key": "Anthropic API 密钥",
    "You can put in your Anthropic key to use Claude at cost. When enabled, this key will be used for all models beginning with \"claude-\".": "你可以填写你的 Anthropic 密钥，以按成本使用 Claude。启用后，此密钥将用于所有以 \"claude-\" 开头的模型。",
    "your Anthropic key": "你的 Anthropic 密钥",
    "to use Claude at cost. When enabled, this key will be used for all models beginning with \"claude-\".": "以按成本使用 Claude。启用后，此密钥将用于所有以 \"claude-\" 开头的模型。",
    " to use Claude at cost. When enabled, this key will be used for all models beginning with \"claude-\".": "，以按成本使用 Claude。启用后，此密钥将用于所有以 \"claude-\" 开头的模型。",
    "Enter your Anthropic API Key": "请输入 Anthropic API 密钥",
    "Google API Key": "Google API 密钥",
    "You can put in your Google AI Studio key to use Google models at-cost.": "你可以填写你的 Google AI Studio 密钥，以按成本使用 Google 模型。",
    "your Google AI Studio key": "你的 Google AI Studio 密钥",
    "to use Google models at-cost.": "以按成本使用 Google 模型。",
    " to use Google models at-cost.": "，以按成本使用 Google 模型。",
    "Enter your Google AI Studio API Key": "请输入 Google AI Studio API 密钥",
    "Enter your Azure OpenAI API Key": "请输入 Azure OpenAI API 密钥",
    "Azure OpenAI": "Azure OpenAI",
    "Configure Azure OpenAI to use OpenAI models through your Azure account.": "配置 Azure OpenAI，通过你的 Azure 账号使用 OpenAI 模型。",
    "Base URL": "基础 URL",

    "Approvals & Execution for commands, MCP and more": "命令、MCP 等审批与执行",
    "Run Mode": "运行模式",
    "Auto-Run Mode": "自动运行模式",
    "Execution and Approvals": "执行与审批",
    "Choose how Agents run tools like command execution, MCP, and file writes.": "选择智能体如何运行命令执行、MCP 和文件写入等工具。",
    "Choose how Agent runs tools like command execution, MCP, and file writes.": "选择智能体如何运行命令执行、MCP 和文件写入等工具。",
    "Commands that are allowlisted will run automatically.": "列入白名单的命令将自动运行。",
    "Command Allowlist": "命令白名单",
    "Commands that can run automatically": "可自动运行的命令",
    "MCP Allowlist": "MCP 白名单",
    "MCP tools that can run automatically. Format: 'server:tool', 'server:*' for all tools from a server, '*:tool' for a tool from any server, or *:* for all tools from all servers": "可自动运行的 MCP 工具。格式：'server:tool'、'server:*' 表示某服务器的全部工具、'*:tool' 表示任意服务器的某工具、*:* 表示所有服务器的所有工具",
    "Fetch Domain Allowlist": "请求域名白名单",
    "Domains that Agent can fetch from automatically. Use '*' for all domains, '*.example.com' for wildcard subdomains.": "智能体可自动请求的域名。使用 '*' 匹配所有域名，'*.example.com' 匹配通配符子域名。",
    "Auto-Run Network Access": "自动运行网络访问",
    "Control which network requests are allowed when commands run in the sandbox. Edit allowed/denied domains in sandbox.json in your workspace.": "控制命令在沙盒中运行时允许哪些网络请求。可在工作区的 sandbox.json 中编辑允许或拒绝的域名。",
    "Auto-Approved Mode Transitions": "自动批准的模式切换",
    "Mode transitions that will be automatically approved without prompting.": "无需提示即自动批准的模式切换。",
    "Browser Protection": "浏览器保护",
    "Prevent Agent from automatically running Browser tools": "阻止智能体自动运行浏览器工具",
    "MCP Tools Protection": "MCP 工具保护",
    "Prevent Agent from automatically running MCP tools": "阻止智能体自动运行 MCP 工具",
    "File-Deletion Protection": "文件删除保护",
    "Prevent Agent from deleting files automatically": "阻止智能体自动删除文件",
    "External-File Protection": "外部文件保护",
    "Prevent Agent from creating or modifying files outside of the workspace automatically": "阻止智能体自动创建或修改工作区外的文件",
    "Default Location": "默认位置",
    "Where to open new agents": "新智能体的打开位置",
    "Text Size": "文字大小",
    "Adjust the conversation text size": "调整对话文字大小",
    "Ask Every Time": "每次询问",
    "Allowlist": "白名单",
    "Use Allowlist": "使用白名单",
    "Run Everything": "运行所有",
    "Auto-Run in Sandbox": "在沙盒中自动运行",
    "Run Everything (Unsandboxed)": "运行所有（非沙盒）",
    "Ask for permission before running each operation": "每次操作前请求许可",
    "Automatically run operations after you approve them once": "在您批准一次后自动运行操作",
    "Automatically run all operations without asking for permission": "无需请求许可，自动运行所有操作",
    "Tools will auto-run in a sandbox if possible, otherwise respect the allowlist or ask for approval": "工具会尽可能在沙盒中自动运行，否则遵循白名单或请求批准",
    "sandbox.json Only": "仅 sandbox.json",
    "sandbox.json + Defaults": "sandbox.json + 默认值",
    "Allow All": "全部允许",
    "Sandboxed network access is disabled by your admin.": "沙盒网络访问已被管理员禁用。",
    "Sandboxed network access is controlled by your admin. You can still edit allowed/denied domains in sandbox.json in your workspace, but admin policy takes precedence.": "沙盒网络访问由管理员控制。您仍可在工作区的 sandbox.json 中编辑允许或拒绝的域名，但管理员策略优先。",
    "Smart Allowlist": "智能白名单",
    "Use AI-powered command classification to intelligently match commands against allowlist patterns and suggest sandbox modes": "使用 AI 命令分类智能匹配白名单模式并建议沙盒模式",
    "Settings": "设置",
    "Extra Large": "超大",
    "Cursor Tab": "Cursor Tab 补全",
    "Window Layout": "窗口布局",
    "Switch between Agent and Editor default layouts": "在智能体和编辑器默认布局之间切换",
    "Title Bar": "标题栏",
    "Show title bar in agent layout": "在智能体布局中显示标题栏",
    "Show status bar at the bottom of the window": "在窗口底部显示状态栏",
    "Review Control Location": "审查控件位置",
    "Show inline diff review controls in top level breadcrumbs or floating island": "在顶部面包屑或浮动面板中显示内联差异审查控件",
    "Breadcrumb": "面包屑",
    "Island": "浮动面板",
    "Context-aware, multi-line suggestions around your cursor based on recent edits": "基于最近编辑，在光标周围提供上下文感知的多行建议",
    "Partial Accepts": "部分接受",
    "Accept the next word of a suggestion via Ctrl+RightArrow": "通过 Ctrl+右箭头接受建议的下一个单词",
    "Suggestions While Commenting": "注释时建议",
    "Allow Tab to trigger while in a comment region": "允许在注释区域中触发 Tab 补全",
    "Whitespace-Only Suggestions": "仅空白建议",
    "Suggest edits like new lines and indentation that modify whitespace only": "仅建议修改空白的编辑，如换行和缩进",
    "Automatically import necessary modules for TypeScript": "自动导入 TypeScript 所需的模块",
    "Auto Import for Python": "Python 自动导入",
    "Enable auto import for Python. This is a beta feature.": "启用 Python 自动导入。这是一个测试功能。",
    "Provide domain-specific knowledge and workflows for the agent": "为智能体提供特定领域的知识和工作流",
    "Include third-party Plugins, Skills, and other configs": "包含第三方插件、技能和其他配置",
    "Automatically import agent configs from other tools": "自动从其他工具导入智能体配置",
    "Use Rules to guide agent behavior, like enforcing best practices or coding standards. Rules can be applied always, by file path, or manually.": "使用规则引导智能体行为，例如强制执行最佳实践或编码标准。规则可以始终应用、按文件路径应用或手动应用。",
    "No Rules Yet": "暂无规则",
    "Create rules to guide Agent behavior": "创建规则来引导智能体行为",
    "New User Rule": "新建用户规则",
    "New Project Rule": "新建项目规则",
    "Could Not Load Rules": "无法加载规则",
    "Failed to load workspace rules.": "加载工作区规则失败。",
    "Loading Rules...": "正在加载规则...",
    "Rule content...": "规则内容...",
    "Style request, response language, tone...": "风格要求、回复语言、语气...",
    "Applied intelligently": "智能应用",
    "Content is required.": "内容不能为空。",
    "File pattern is required when applying to specific files.": "应用到指定文件时必须填写文件模式。",
    "Failed to save changes. Please try again.": "保存失败，请重试。",
    "Incorrect format, fix with agent": "格式不正确，使用智能体修复",
    "Delete Rule": "删除规则",
    "Cannot delete team rules": "无法删除团队规则",
    "Show all": "显示全部",
    "Show less": "收起",
    "[Untitled]": "[未命名]",
    "Skills are specialized capabilities that help the agent accomplish specific tasks. Skills will be invoked by the agent when relevant or can be triggered manually with / in chat.": "技能是帮助智能体完成特定任务的专业能力。智能体会在相关时自动调用技能，也可在聊天中通过 / 手动触发。",
    "No Skills Yet": "暂无技能",
    "Skills help the agent accomplish specific tasks": "技能帮助智能体完成特定任务",
    "New Skill": "新建技能",
    "Could Not Load Skills": "无法加载技能",
    "Failed to load workspace skills.": "加载工作区技能失败。",
    "Loading Skills...": "正在加载技能...",
    "Create specialized agents for complex tasks. Subagents can be invoked by the agent to handle focused work in parallel.": "创建用于复杂任务的专业智能体。子智能体可被主智能体调用，以并行处理专项工作。",
    "No Subagents Yet": "暂无子智能体",
    "Create specialized agents to handle focused tasks": "创建专业智能体来处理专项任务",
    "New Subagent": "新建子智能体",
    "Could Not Load Subagents": "无法加载子智能体",
    "Failed to load workspace subagents.": "加载工作区子智能体失败。",
    "Loading Subagents...": "正在加载子智能体...",
    "Create reusable workflows triggered with / prefix in chat. Use commands to standardize processes and make common tasks more efficient.": "创建在聊天中通过 / 前缀触发的可复用工作流。使用命令标准化流程，提高常见任务的效率。",
    "No Commands Yet": "暂无命令",
    "Create commands to build reusable workflows": "创建命令以构建可复用工作流",
    "New Command": "新建命令",
    "Could Not Load Commands": "无法加载命令",
    "Failed to load workspace commands.": "加载工作区命令失败。",
    "Loading Commands...": "正在加载命令...",
    "+ New": "+ 新建",

    // ── 智能体设置 ──
    "Conversation": "对话",
    "Auto-Clear Chat": "自动清除聊天",
    "After periods of inactivity, open the Agent Pane to a new conversation": "一段时间不活动后，将智能体面板打开为新对话",
    "Submit with ⌘ + Enter": "使用 ⌘ + Enter 提交",
    "Submit with Ctrl + Enter": "使用 Ctrl + Enter 提交",
    "When enabled, ⌘ + Enter submits chat and Enter inserts a newline": "启用后，⌘ + Enter 提交聊天，Enter 插入换行",
    "When enabled, Ctrl + Enter submits chat and Enter inserts a newline": "启用后，Ctrl + Enter 提交聊天，Enter 插入换行",
    "Ctrl+Enter submits chat, Enter inserts a newline, and primary actions move to Ctrl+Alt+Enter": "Ctrl+Enter 提交聊天，Enter 插入换行，主要操作改为 Ctrl+Alt+Enter",
    "Max Tab Count": "最大标签页数",
    "Limit how many chat tabs can be open at once": "限制同时打开的聊天标签页数量",
    "Queue Messages": "消息队列",
    "Adjust the default behavior of sending a message while Agent is running": "调整智能体运行时发送消息的默认行为",
    "Send after current message": "当前消息后发送",
    "Send After Current Message": "当前消息后发送",
    "Send Right Away": "立即发送",
    "Stop & send right away": "立即停止并发送",
    "Usage Summary": "用量摘要",
    "When to show the usage summary at the bottom of the chat pane": "何时在聊天面板底部显示用量摘要",
    "Agent Autocomplete": "智能体自动补全",
    "Contextual suggestions while prompting Agent": "向智能体提问时提供上下文建议",
    "Authentication error": "身份验证错误",
    "If you are logged in, try logging out and back in.": "如果您已登录，请尝试退出后重新登录。",
    "Copy Request": "复制请求",

    // ── Agent Review ──
    "Start Agent Review on Commit": "代码提交时启动智能体审查",
    "Automatically review your changes for issues after each commit": "在每次提交后自动审查您的更改是否存在问题",
    "Include Submodules in Agent Review": "在智能体审查中包含子模块",
    "Include changes from Git submodules in the review": "在审查中包含 Git 子模块的更改",
    "Include Untracked Files in Agent Review": "在审查中包含未跟踪文件",
    "Include untracked files (new files not yet added to Git) in the review": "在审查中包含未跟踪文件（尚未添加到 Git 的新文件）",
    "Default Approach": "默认方式",
    "Choose between quick or more thorough, higher-cost analysis": "选择快速或更彻底、成本更高的分析",
    "Auto-Approve Mode Transitions": "自动批准模式切换",
    "Allow Agent to switch modes without asking first, such as Agent to Plan or Agent to Debug. When off, Cursor asks before switching.": "允许智能体在不先询问的情况下切换模式，例如从智能体切换到计划或调试。关闭时，Cursor 会在切换前询问。",
    "Subagents": "子智能体",
    "Explore subagent model": "探索子智能体模型",
    "Choose Explore subagent model": "选择探索子智能体模型",
    "The Explore subagent is used to do initial research for the main agent": "探索子智能体用于为主智能体进行初始研究",
    "Select model": "选择模型",
    "Select model count": "选择模型数量",
    "Inherit from parent": "继承父级设置",
    "Reset to default": "重置为默认值",
    "Max Mode required": "需要 Max 模式",
    "Subagent model overrides will only be used in Max Mode": "子智能体模型覆盖仅会在 Max 模式中使用",
    "Follow-Up Prompt Suggestions": "后续提示建议",
    "Suggest a follow-up for the Agent": "为智能体建议后续提示",

    // ── Context & Applied Changes ──
    "Context and Tools": "上下文与工具",
    "Web Search Tool": "网络搜索工具",
    "Allow Agent to search the web for relevant information": "允许智能体在网络上搜索相关信息",
    "Auto-Accept Web Search": "自动接受网络搜索",
    "Skip approval dialog; Agent may run web searches automatically": "跳过批准对话；智能体可自动运行网络搜索",
    "Web Fetch Tool": "网页获取工具",
    "Allow Agent to fetch content from URLs": "允许智能体从 URL 获取内容",
    "Hierarchical Cursor Ignore": "分层 Cursor 忽略",
    "Apply .cursorignore files to all subdirectories. Changing this setting will require a restart of Cursor.": "将 .cursorignore 文件应用到所有子目录。更改此设置需要重启 Cursor。",
    "Ignore Symlinks in Cursor Ignore Search": "在 Cursor 忽略搜索中忽略符号链接",
    "Use with caution. Skip symlinks during .cursorignore file discovery. Only enable if your repository has many symlinks and all .cursorignore files are reachable without them. Changing this setting will require a restart of Cursor.": "谨慎使用。在发现 .cursorignore 文件时跳过符号链接。仅当您的仓库存有许多符号链接，且没有符号链接也能访问所有 .cursorignore 文件时才启用。更改此设置需要重启 Cursor。",
    "Applying Changes": "应用更改",
    "Inline Diffs": "内联差异",
    "Show inline diff decorations in the editor instead of only showing changes in the review panel": "在编辑器中显示内联差异装饰，而不是仅在审查面板中显示更改",
    "Jump to Next Diff on Accept": "接受时跳转到下一个差异",
    "Automatically jump to the next diff when accepting changes with Ctrl+Y": "使用 Ctrl+Y 接受更改时自动跳转到下一个差异",
    "Auto Format on Agent Finish": "智能体完成时自动格式化",
    "Automatically format files when the agent finishes": "智能体完成任务时自动格式化文件",

    // ── Inline Editing & Terminal ──
    "Inline Editing & Terminal": "内联编辑与终端",
    "Legacy Terminal Tool": "旧版终端工具",
    "Use the legacy terminal tool in agent mode, for use on systems with unsupported shell configurations": "在智能体模式下使用旧版终端工具，适用于 shell 配置不受支持的系统",
    "Toolbar on Selection": "选中时显示工具栏",
    "Show Add to Chat & Quick Edit buttons when selecting code": "选择代码时显示“添加到聊天”和“快速编辑”按钮",
    "Auto-Parse Links": "自动解析链接",
    "Automatically parse links when pasted into Quick Edit (Ctrl+K) input": "粘贴到快速编辑 (Ctrl+K) 输入框时自动解析链接",
    "Themed Diff Backgrounds": "主题差异背景",
    "Use themed background colors for inline code diffs": "为内联代码差异使用主题背景色",
    "Terminal Hint": "终端提示",
    "Show a hint for Ctrl+K in the Terminal": "在终端中显示 Ctrl+K 提示",
    "Preview Box for Terminal Ctrl+K": "终端 Ctrl+K 的预览框",
    "Use a preview box instead of streaming responses directly into the shell": "使用预览框而不是将响应直接流式传输到 shell 中",
    "Collapse Auto-Run Commands": "折叠自动运行命令",
    "Collapse auto-run command output by default in Terminal command previews": "在终端命令预览中默认折叠自动运行的命令输出",

    // ── Voice Mode & Attribution ──
    "Voice Mode": "语音模式",
    "Submit Keywords": "提交关键字",
    "Custom keywords that trigger auto-submit in voice mode. Only single words (no spaces) are allowed. Punctuation and capitalization are ignored.": "在语音模式下触发自动提交的自定义关键字。仅允许单个单词（无空格）。忽略标点符号和大小写。",
    "Attribution": "代码署名",
    "Commit Attribution": "提交署名",
    "Mark Agent commits as 'Made with Cursor'": "将智能体提交标记为 'Made with Cursor'",
    "PR Attribution": "PR 署名",
    "Mark pull requests as made with Cursor": "将拉取请求标记为使用 Cursor 制作",

    // ── Git ──
    "Branch Prefix": "分支前缀",
    "Prefix for new branches created by Agent (e.g., cursor/, username/)": "智能体创建新分支时使用的前缀（例如 cursor/、username/）",

    // ── Privacy ──
    "Privacy Mode": "隐私模式",
    "Privacy Mode (Legacy)": "隐私模式（旧版）",
    "Your code data will not be trained on or used to improve the product. Code may be stored to provide features such as Background Agent.": "您的代码数据不会被用于训练或改进产品。代码可能会被存储以提供后台智能体等功能。",
    "Your code data will not be trained on or used to improve the product. We will not store your code.": "您的代码数据不会被用于训练或改进产品。我们不会存储您的代码。",
    "Privacy Mode (Legacy) is enabled. Background Agent and some features not available.": "隐私模式（旧版）已启用。后台智能体和部分功能不可用。",
    "Switch to Privacy Mode": "切换到隐私模式",
    "Data Sharing is controlled by the team admin. Configure here.": "数据共享由团队管理员控制。在此配置。",
    "Share Data": "共享数据",
    "Improve Cursor for everyone": "帮助所有人改进 Cursor",
    "No training. Code may be stored for Background Agent and other features.": "不用于训练。代码可能会被存储，以支持后台智能体和其他功能。",
    "No training and no storage. Background Agent and other features that require code storage will be disabled.": "不用于训练，也不存储。后台智能体和其他需要代码存储的功能将被禁用。",
    "More Options": "更多选项",

    // ── Miscellaneous ──
    "Accept the next word of a suggestion via Ctrl+RightArrow": "通过 Ctrl+RightArrow 接受建议的下一个词",
    "Automatically import necessary modules for TypeScript": "自动为 TypeScript 导入必要的模块",

    // ── Usage Limits ──
    "Increase limits for faster responses": "提高限制以获得更快的响应",
    "You're over your current usage limit and your requests are being processed with Auto in the slow queue.": "您已超出当前配置的使用量限制，您的请求正以临时排队方式在慢速队列中处理。",
    "Set new limit": "设置新限制",
    "On-Demand Usage": "按需用量",
    "On-Demand Spending": "按需消费",
    "On-Demand usage is consumed after a usage limit is reached, and is billed in arrears.": "达到用量限制后会消耗按需用量，并在之后计费。",
    "On-demand spending is currently disabled": "按需消费当前已禁用",
    "Monthly Limit": "月度限额",
    "Set a fixed amount or make it unlimited.": "设置固定额度，或设为无限制。",
    "Your plan includes at least $": "您的套餐至少包含 $",
    " of API usage.": " 的 API 用量。",

    // ── Cloud / Background Agents ──
    "Get Started": "开始使用",
    "Cloud Agents Unavailable": "云端智能体不可用",
    "Cloud Agents require data storage to function.": "云端智能体需要数据存储才能运行。",
    "Privacy Mode Enabled": "隐私模式已启用",
    "Cloud Agents are not available when your privacy mode is set to disable data storage. To use Cloud Agents, please update your privacy settings to allow data storage.": "当隐私模式设置为禁用数据存储时，云端智能体不可用。要使用云端智能体，请更新隐私设置以允许数据存储。",
    "Open Privacy Settings": "打开隐私设置",
    "Cloud Agents require a Git repository in an open folder.": "云智能体需要打开的文件夹中包含 Git 仓库。",
    "Loading Cloud Agents settings...": "正在加载云端智能体设置...",
    "Open a folder that contains a Git repository to configure Cloud Agents.": "打开包含 Git 仓库的文件夹以配置云端智能体。",
    "Manage Settings": "管理设置",
    "Open a Git repository": "打开 Git 仓库",
    "Background agents only work in folders with a git repository.": "后台智能体仅在包含 git 仓库的文件夹中工作。",
    "Please open a folder that contains a git repository to use this feature.": "请打开包含 git 仓库的文件夹以使用此功能。",

    // ── Extensions / Marketplace ──
    "No Plugins": "暂无插件",
    "Browse the marketplace or import custom plugins to extend Cursor with Skills, Rules, Agents, Hooks, and MCPs.": "浏览插件市场或导入自定义插件，用技能、规则、智能体、钩子和 MCP 扩展 Cursor。",
    "Browse the marketplace or import custom plugins to extend": "浏览插件市场或导入自定义插件来扩展",
    "Cursor with Skills, Rules, Agents, Hooks, and MCPs.": "Cursor 的技能、规则、智能体、钩子和 MCP。",
    "Add Plugin": "添加插件",
    "Add Plugins": "添加插件",
    "Search the marketplace": "搜索插件市场",
    "Loading plugins...": "正在加载插件...",
    "No result": "无结果",
    "No Result": "无结果",
    "No results": "无结果",
    "No results found": "未找到结果",
    "No Results": "无结果",
    "No Results Found": "未找到结果",
    "No files found": "未找到文件",
    "No matches found": "未找到匹配项",
    "No plugins found": "未找到插件",
    "No plugins found in this repository.": "此仓库中未找到插件。",
    "No plugins match your search.": "没有插件匹配你的搜索。",
    "Try changing your search query": "请尝试修改搜索条件",
    "Try a different search term or browse by category": "请尝试其他搜索词或按分类浏览",
    "Try different filters": "请尝试不同筛选条件",
    "All plugins have been added.": "所有插件均已添加。",
    "All plugins from this repository have already been added.": "此仓库中的所有插件均已添加。",
    "Add plugins or import from GitHub to make them available for your team.": "添加插件或从 GitHub 导入，使团队可以使用它们。",
    "Import Marketplace...": "导入插件市场...",
    "Manage plugins": "管理插件",
    "Extend Cursor with Skills, Rules, Agents, Hooks, and MCPs": "使用技能、规则、智能体、钩子和 MCP 扩展 Cursor",
    "Browse MCPs": "浏览 MCP",
    "Search anything": "搜索任何内容",
    "Browse Marketplace": "浏览插件市场",

    // ── Common visible UI states ──
    "Rendering diagram...": "正在渲染图表...",
    "Mermaid Syntax Error": "Mermaid 语法错误",
    "View diagram source": "查看图表源码",
    "Open in Terminal Pane": "在终端面板中打开",
    "Add to Allowlist and Run": "添加到白名单并运行",
    "Empty directory": "空目录",
    "No diagnostics found": "未发现诊断信息",
    "No MCP resources available": "暂无可用 MCP 资源",
    "Waiting for upload...": "正在等待上传...",
    "This agent was working on ": "此智能体正在处理 ",
    "Don't ask again": "不再询问",
    "Stay on Current Branch": "留在当前分支",
    "Agent disconnected": "智能体已断开连接",
    "Context Usage": "上下文用量",
    "Show context usage": "显示上下文用量",
    "Search or Paste Link": "搜索或粘贴链接",
    "OAuth Client ID (optional)": "OAuth 客户端 ID（可选）",
    "OAuth Client Secret (optional)": "OAuth 客户端密钥（可选）",
    "Add MCP Server": "添加 MCP 服务器",
    "Clear variables": "清除变量",
    "Plugin Settings": "插件设置",
    "Marketplace Settings": "插件市场设置",
    "Marketplace Access": "插件市场访问权限",
    "Select who can see and use plugins from this team marketplace": "选择谁可以查看和使用此团队插件市场中的插件",
    "Enable Auto Refresh": "启用自动刷新",
    "Automatically update plugins when changes are pushed to the repository": "当变更推送到仓库时自动更新插件",
    "Plugin Repository": "插件仓库",
    "Fetch marketplace plugins from the GitHub repository": "从 GitHub 仓库获取插件市场插件",
    "Remove Marketplace": "移除插件市场",
    "Remove marketplace?": "移除插件市场？",
    "Delete Marketplace": "删除插件市场",
    "Delete marketplace?": "删除插件市场？",
    "This marketplace and its access settings will be removed. The source repository won't be affected.": "将移除此插件市场及其访问设置。源仓库不会受到影响。",
    "This marketplace and its access settings will be removed. The repository won't be affected.": "将移除此插件市场及其访问设置。仓库不会受到影响。",
    "This marketplace will be removed from your account. The source repository won't be affected.": "将从你的账号中移除此插件市场。源仓库不会受到影响。",
    "Available Marketplaces": "可用插件市场",
    "Access Settings": "访问设置",
    "Plugin Installation": "插件安装",
    "Add for Myself": "为自己添加",
    "Add to Project": "添加到项目",
    "Finishing setup...": "正在完成设置...",
    "Open in Editor": "在编辑器中打开",
    "Open debug logs": "打开调试日志",
    "Restore default parameters": "恢复默认参数",
    "Uncommitted Changes": "未提交变更",
    "Modes, skills, MCPs and more": "模式、技能、MCP 等",
    "Download file": "下载文件",
    "Download image": "下载图片",
    "Open external link?": "打开外部链接？",
    "You're about to visit an external website.": "你即将访问外部网站。",
    "Download diagram": "下载图表",
    "Download diagram as SVG": "下载 SVG 图表",
    "Download diagram as PNG": "下载 PNG 图表",
    "Download diagram as MMD": "下载 MMD 图表",
    "View fullscreen": "全屏查看",
    "Exit fullscreen": "退出全屏",
    "Copy table as CSV": "复制为 CSV 表格",
    "Copy table as TSV": "复制为 TSV 表格",
    "Download table": "下载表格",
    "Download table as CSV": "下载 CSV 表格",
    "Download table as Markdown": "下载 Markdown 表格",
    "Reset zoom and pan": "重置缩放和平移",
    "Loading diagram...": "正在加载图表...",
    "No Automations Yet": "暂无自动化",
    "New Automation": "新建自动化",
    "Run agents on a schedule or automatically in response to events. Billed at plan rates.": "按计划运行智能体，或响应事件自动运行。按套餐费率计费。",
    "No results found.": "未找到结果。",
    "No results for": "没有结果匹配",
    "Search channels or paste channel ID...": "搜索频道或粘贴频道 ID...",
    "Loading channels...": "正在加载频道...",
    "No channels available": "暂无可用频道",
    "Add channel ID ": "添加频道 ID ",
    "Any channel": "任意频道",
    "Selected": "已选择",
    "Manage Marketplace": "管理插件市场",
    "Date range": "日期范围",
    "Rows per page": "每页行数",
    "Search Plugins, Skills, Tools, Subagents, Commands...": "搜索插件、技能、工具、子智能体、命令...",
    "All Marketplaces": "所有插件市场",
    "Debug Logs": "调试日志",
    "Waiting for log entries...": "正在等待日志条目...",
    "Clear Logs": "清空日志",
    "Reproduction Steps": "复现步骤",
    "Mark Fixed": "标记为已修复",
    "Load Diff": "加载差异",
    "Generated files are not rendered by default.": "默认不渲染生成文件。",
    "Large diffs are hidden by default.": "默认隐藏大型差异。",
    "Diff content not available": "差异内容不可用",
    "This file changed, but a text diff could not be rendered.": "此文件已更改，但无法渲染文本差异。",
    "Agent blocked": "智能体已被阻止",
    "Up to date": "已是最新",
    "Ready to save": "准备保存",
    "Setting up": "正在设置",
    "Anything else?": "还有其他问题吗？",
    "Add Models": "添加模型",
    "Your admin has disabled this option.": "你的管理员已禁用此选项。",
    "Show all models...": "显示所有模型...",
    "MAX Mode": "MAX 模式",
    "Use Multiple Models": "使用多个模型",
    "Enable MAX Mode": "启用 MAX 模式",
    "Search models": "搜索模型",
    "No models found": "未找到模型",
    "Move to Local": "移动到本地",
    "Checkout branch locally": "在本地检出分支",
    "Checkout & Move to Local": "检出并移动到本地",
    "Checkout branch and convert agent to local mode": "检出分支并将智能体转换为本地模式",
    "You have uncommitted changes in your working tree. Choose an option, then continue.": "你的工作树中有未提交的更改。请选择一个选项，然后继续。",
    "Do not ask me again": "不再询问我",
    "Paste as one line": "粘贴为一行",
    "Add an agent to get started": "添加一个智能体以开始使用",
    "Todo description...": "待办描述...",
    "Build in New Agent": "在新智能体中构建",
    "Add a to-do to get started": "添加一个待办以开始使用",
    "Add to Chat": "添加到聊天",
    "Plan body...": "计划正文...",
    "Save to workspace": "保存到工作区",
    "Build in Parallel": "并行构建",
    "Copy as Markdown": "复制为 Markdown",
    "Find in Plan": "在计划中查找",
    "Save to Workspace": "保存到工作区",
    "View Plan": "查看计划",
    "Error loading plugin": "加载插件出错",
    "Try in Chat": "在聊天中试用",
    "Import from GitHub": "从 GitHub 导入",
    "Enter a GitHub repository URL containing a plugin marketplace": "输入包含插件市场的 GitHub 仓库 URL",
    "GitHub Repository URL": "GitHub 仓库 URL",
    "Open in Chat": "在聊天中打开",
    "View Details": "查看详情",
    "Remove from Cursor": "从 Cursor 中移除",
    "All files and folders": "所有文件和文件夹",
    "Add Skills": "添加技能",
    "Search MCP servers...": "搜索 MCP 服务器...",
    "Loading MCP servers...": "正在加载 MCP 服务器...",
    "No MCP servers": "暂无 MCP 服务器",
    "No MCP servers available": "暂无可用 MCP 服务器",
    "No MCP servers configured": "未配置 MCP 服务器",
    "No servers match your search": "没有服务器匹配你的搜索",
    "Open MCP Settings": "打开 MCP 设置",
    "Add agents, context, tools...": "添加智能体、上下文、工具...",
    "Loading skills...": "正在加载技能...",
    "No skills available": "暂无可用技能",
    "Waiting for logs": "正在等待日志",
    "SSH Hostname": "SSH 主机名",
    "Type in a host like user@host or select from SSH config": "输入 user@host 形式的主机，或从 SSH 配置中选择",
    "Rename tab": "重命名标签页",
    "Close Others": "关闭其他标签页",
    "Close to the Right": "关闭右侧标签页",
    "Close All": "全部关闭",
    "Commit changes": "提交更改",
    "Create a checkpoint commit with your current changes": "使用当前更改创建检查点提交",
    "Stash changes": "暂存更改",
    "Save your changes to a stash and restore them later": "将更改保存到 stash，稍后可恢复",
    "Discard changes": "放弃更改",
    "Delete your current uncommitted changes before switching": "切换前删除当前未提交的更改",
    "Temporarily save uncommitted work, then check out the cloud agent branch.": "临时保存未提交的工作，然后检出云端智能体分支。",
    "Create a checkpoint commit of your changes, then check out the branch.": "为你的更改创建检查点提交，然后检出该分支。",
    "Hidden from agent": "对智能体隐藏",
    "Leak scanned before commit": "提交前已扫描泄漏",
    "Available at runtime": "运行时可用",
    "Available at build": "构建时可用",
    "No files": "无文件",
    "Most Used": "最常用",
    "Failed to migrate agent": "迁移智能体失败",
    "Change run mode": "更改运行模式",
    "Add to allowlist": "添加到白名单",
    "MCP Servers": "MCP 服务器",
    "Cloud MCP Servers": "云端 MCP 服务器",
    "User MCP Servers": "用户 MCP 服务器",
    "Team MCP Servers": "团队 MCP 服务器",
    "Workspace MCP Servers": "工作区 MCP 服务器",
    "Home MCP Servers": "Home MCP 服务器",
    "Workspace MCP Tools": "工作区 MCP 工具",
    "Servers available to cloud agents.": "可供云端智能体使用的服务器。",
    "Servers available in this workspace.": "此工作区可用的服务器。",
    "Servers available from Home.": "Home 中可用的服务器。",
    "Sign In to View Cloud MCP Servers": "登录以查看云端 MCP 服务器",
    "Could Not Load Cloud MCP Servers": "无法加载云端 MCP 服务器",
    "Could Not Load Workspace MCP Servers": "无法加载工作区 MCP 服务器",
    "No User MCP Servers": "暂无用户 MCP 服务器",
    "No Team MCP Servers": "暂无团队 MCP 服务器",
    "Loading cloud MCP servers...": "正在加载云端 MCP 服务器...",
    "Loading user MCP servers...": "正在加载用户 MCP 服务器...",
    "Loading team MCP servers...": "正在加载团队 MCP 服务器...",
    "Loading workspace MCP servers...": "正在加载工作区 MCP 服务器...",
    "Failed to load cloud MCP servers.": "加载云端 MCP 服务器失败。",
    "Failed to load workspace MCP servers.": "加载工作区 MCP 服务器失败。",
    "Your personal cloud MCP servers.": "你的个人云端 MCP 服务器。",
    "Cloud MCP servers shared by your team.": "团队共享的云端 MCP 服务器。",
    "Add a personal cloud MCP server to make it available to your cloud agents.": "添加个人云端 MCP 服务器，使云端智能体可以使用它。",
    "Team admins can configure shared MCP servers in the dashboard.": "团队管理员可在控制台配置共享 MCP 服务器。",
    "Open Dashboard": "打开控制台",
    "Add MCP": "添加 MCP",
    "Mermaid Diagram": "Mermaid 图表",
    "Tree outline": "树形大纲",
    "Apply to Specific Files & Folders": "应用到指定文件和文件夹",
    "Always applied": "始终应用",
    "Agent decides when to apply": "由智能体决定何时应用",
    "Create with Agent": "使用智能体创建",
    "Saving...": "正在保存...",
    "Plan and design before coding...": "编码前先规划和设计...",
    "Plan and design before coding": "编码前先规划和设计",
    "Debug and troubleshoot issues...": "调试并排查问题...",
    "Debug and troubleshoot issues": "调试并排查问题",
    "Ask questions without making changes...": "提问但不修改...",
    "Ask questions without making changes": "提问但不修改",
    "Files & Folders": "文件和文件夹",
    "Agent Stores": "智能体存储",
    "Past Chats": "历史聊天",
    "Branch (Diff with Main)": "分支（与 Main 对比）",
    "Mentions": "提及项",
    "Terminals": "终端",
    "Grep Search": "Grep 搜索",
    "Search files": "搜索文件",
    "Searching files": "正在搜索文件",
    "Searched files": "已搜索文件",
    "Search files attempted": "已尝试搜索文件",
    "Search files...": "搜索文件...",
    "Search actions...": "搜索操作...",
    "Search agents...": "搜索智能体...",
    "Search files, actions, agents...": "搜索文件、操作、智能体...",
    "Files": "文件",
    "Actions": "操作",
    "Files in workspace": "工作区文件",
    "Edit & Reapply": "编辑并重新应用",
    "Delete file": "删除文件",
    "Enable Run Everything?": "启用“运行所有”？",
    "Enable Run Everything": "启用运行所有",
    "Leave Ask Every Time?": "离开“每次询问”？",
    "Use Sandbox instead": "改用沙盒",
    "Use Allowlist instead": "改用白名单",
    "Continue": "继续",
    "Unsupported Model": "不支持的模型",
    "The model \"": "模型 \"",
    "\" is not supported. Please choose a different model.": "\" 不受支持。请选择其他模型。",
    "Connection stalled": "连接停滞",
    "Connection stalled repeatedly": "连接反复停滞",
    "The connection stalled. Please try again.": "连接停滞。请重试。",
    "Connection failed": "连接失败",
    "Connection failed repeatedly": "连接反复失败",
    "Connection failed. Please try again, or contact support if the issue persists.": "连接失败。请重试；如果问题持续存在，请联系支持。",
    "Connection failed. If the problem persists, please check your internet connection or VPN": "连接失败。如果问题持续存在，请检查你的网络连接或 VPN",
    "Clear the conversation and start fresh": "清空对话并重新开始",
    "Summarize the conversation": "总结对话",
    "Request an agent to review your code": "请求智能体审查你的代码",
    "Open Browser": "打开浏览器",
    "Open a browser for web interactions": "打开浏览器进行网页交互",
    "Install a plugin from the marketplace": "从插件市场安装插件",
    "Browse and install plugins from the Cursor marketplace. Type a search query after the command to find plugins.": "从 Cursor 插件市场浏览并安装插件。在命令后输入搜索词以查找插件。",
    "Uninstall an installed plugin": "卸载已安装插件",
    "Remove an installed plugin. Type a search query after the command to find plugins to uninstall.": "移除已安装插件。在命令后输入搜索词以查找要卸载的插件。",
    "Reset": "重置",
    "Summarize": "总结",

    // ── Agent errors ──
    "Agent Execution Timed Out": "智能体执行超时",
    "The agent execution provider did not respond in time. This may indicate the extension host is not running or is unresponsive.": "智能体执行提供程序未及时响应。这可能表示扩展主机未运行或无响应。",
    "Extensions have been modified on disk. Please reload the window.": "扩展已在磁盘上修改。请重新加载窗口。",
    "Extensions have been modified on disk.": "扩展已在磁盘上修改。",
    "Please reload the window.": "请重新加载窗口。",
    "Cannot reconnect. Please reload the window.": "无法重新连接。请重新加载窗口。",
    "Reload Window": "重新加载窗口",
    "&&Reload Window": "&&重新加载窗口",

    // ── Network ──
    "HTTP Compatibility Mode": "HTTP 兼容模式",
    "HTTP/2 is recommended for low-latency streaming. In some corporate proxy and VPN environments, the compatibility mode may need to be lowered.": "推荐使用 HTTP/2 以实现低延迟流式传输。在某些企业代理和 VPN 环境中，可能需要降低兼容模式。",
    "Required Domains": "必需的域名",
    "These domains must be accessible for Cursor to function. Add them to your firewall or proxy allowlist.": "必须可访问这些域名，Cursor 才能正常工作。请将它们添加到您的防火墙或代理白名单中。",
    "Network Diagnostics": "网络诊断",
    "Check network connectivity to all Cursor services": "检查与所有 Cursor 服务的网络连接",

    // ── Update ──
    "Update Access": "更新通道",
    "By default, get notifications for stable updates. In Early Access, pre-release builds may be unstable for production work.": "默认情况下，接收稳定版更新的通知。在抢先体验通道中，预发布版本可能不稳定，不建议用于生产环境。",
    "Extension RPC Tracer": "扩展 RPC 追踪器",
    "Log extension host RPC messages to JSON files viewable in Perfetto for performance analysis. Requires a restart to take effect.": "将扩展主机的 RPC 消息记录到 JSON 文件中，可在 Perfetto 中查看以进行性能分析。需要重启才能生效。",

    // ── Hooks ──
    "Hooks let you run custom scripts at specific points during the agent's execution to modify behavior, enforce policies, or add custom logging.": "钩子允许您在智能体执行的特定点运行自定义脚本，以修改行为、强制执行策略或添加自定义日志。",
    "Configured Hooks": "已配置的钩子",
    "Configuration Errors": "配置错误",
    "Add a hooks.json file to your user, project, or enterprise config to start running custom scripts.": "在用户、项目或企业配置中添加 hooks.json 文件，即可开始运行自定义脚本。",
    "No hooks configured": "未配置钩子",
    "No hook executions yet": "暂无钩子执行记录",

    // ── Tools / Browser ──
    "Authentication": "身份验证",
    "Wait for MCP Authentication": "等待 MCP 身份验证",
    "Wait indefinitely to authenticate when prompted. When off, skip authentication prompts after 30 seconds.": "出现身份验证提示时会一直等待。关闭后，30 秒后跳过身份验证提示。",
    "Browser Automation": "浏览器自动化",
    "Connected to Browser Tab": "已连接到浏览器标签页",
    "Browser automation disabled": "浏览器自动化已禁用",
    "Checking status...": "正在检查状态...",
    "Show Localhost Links in Browser": "在浏览器中显示 Localhost 链接",
    "Automatically open localhost links in the Browser Tab": "自动在浏览器标签页中打开 localhost 链接",

    // ── Features / Documentation Links ──
    "Learn about Rules": "了解规则",
    "Learn about Skills": "了解技能",
    "Learn about Subagents": "了解子智能体",
    "Learn about Commands": "了解命令",
    "Learn more": "了解更多",
    "User Rule": "用户规则",
    "Project Rule": "项目规则",
    "Add from GitHub/GitLab": "从 GitHub/GitLab 添加",

    // ── Commands & MCP ──
    "Project Command": "项目命令",
    "User Command": "用户命令",
    "New MCP Server": "新建 MCP 服务器",
    "Add a Custom MCP Server": "添加自定义 MCP 服务器",
    "Open JSON": "打开 JSON",
    "Open user config": "打开用户配置",
    "Open project config": "打开项目配置",
    "Open enterprise config": "打开企业配置",

    // ── PR / Layout ──
    "Pull Requests": "拉取请求",
    "Review Provider": "评审提供方",
    "Choose GitHub or Graphite for pull request links on web and desktop": "选择 GitHub 或 Graphite 作为网页和桌面端 PR 链接打开方式",
    "PR Link Destination": "PR 链接打开位置",
    "Open pull request links inside Cursor or in the default browser": "在 Cursor 内或默认浏览器中打开拉取请求链接",
    "Inside Cursor": "Cursor 内打开",
    "Default browser": "默认浏览器",
    "Team default": "团队默认值",
    "PR Preferences": "PR 偏好设置",
    "Preferred PR destination": "首选 PR 打开位置",
    "Choose where PR links open across web, the desktop app and IDE.": "选择 PR 链接在网页、桌面应用和 IDE 中的打开位置。",
    "Open chat as editor tabs": "以编辑器标签页打开聊天",
    "Show chats as editor tabs inside the chat area instead of the legacy stacked view": "在聊天区域内以编辑器标签页显示聊天，而不是旧版堆叠视图",
    "Open chat as editor tabs is unavailable while non-chat content is placed in the Secondary Side Bar.": "当辅助侧边栏中放置了非聊天内容时，无法以编辑器标签页打开聊天。",
    "Ignored Files": "忽略的文件",
    "Configure Ignored Files": "配置忽略文件",
    "Glob patterns for files where Cursor Tab will not suggest": "Cursor Tab 不提供建议的文件 Glob 匹配模式",

    // ── Composer modes ──
    "Plan, search, make edits, run commands": "规划、搜索、编辑并运行命令",
    "Plan, search, build anything": "规划、搜索、构建任何内容",
    "Systematically diagnose and fix bugs using runtime traces": "使用运行时追踪系统地诊断并修复问题",
    "Coordinate long-horizon tasks with delegated subagents": "通过委派子智能体协调长期任务",
    "Create detailed plans for accomplishing tasks": "为完成任务创建详细计划",
    "Create structured plans with implementation steps": "创建包含实现步骤的结构化计划",
    "Run and coordinate multiple tasks in parallel": "并行运行并协调多个任务",
    "Ask Cursor questions about your codebase": "向 Cursor 询问有关代码库的问题",
    "Special conversation mode for project-level discussions": "用于项目级讨论的特殊对话模式",
    "Open Agents Window on startup": "启动时打开 Agents Window",
    "When launching Cursor, open Agents Window by default": "启动 Cursor 时默认打开 Agents Window",
    "Open Agents Window on Startup": "启动时打开 Agents Window",
    "Open the Agents Window by default when Cursor launches": "Cursor 启动时默认打开 Agents Window",
    "Plan, Build, / for skills, @ for context": "规划、构建，/ 选择技能，@ 添加上下文",
    "Ask, learn, brainstorm": "提问、学习、头脑风暴",
    "Work on explicitly added files (no tools)": "处理明确添加的文件（不使用工具）",
    "Reject, suggest, follow up?": "拒绝、建议或继续追问？",
    "Continue locally": "在本地继续",
    "Ask follow-ups in the worktree": "在工作树中继续追问",
    "Add a follow-up": "添加追问",
    "Drop here to attach...": "拖到此处添加附件...",
    "Split Up": "向上拆分",
    "Split Down": "向下拆分",
    "Split Left": "向左拆分",
    "Split Right": "向右拆分",
    "Split in Group": "在组内拆分",

    // ── Models ──
    "Balanced quality and speed, recommended for most tasks": "平衡质量和速度，推荐用于大多数任务",
    "Multiple models require a Git repository.": "使用多模型功能需要 Git 仓库。",

    // ── Dialogs ──
    "Are you sure? This replaces your settings and extensions with your vscode ones. This cannot be undone.": "确定要继续吗？这将用您的 VS Code 设置和扩展替换当前的设置和扩展。此操作无法撤销。",
    "Reset \"Don't Ask Again\" Dialogs": "重置“不再询问”弹窗",
    "Reset \"Don’t Ask Again\" Dialogs": "重置“不再询问”弹窗",
    "See warnings and tips that you've hidden": "查看您已隐藏的警告和提示",
    "See warnings and tips that you’ve hidden": "查看您已隐藏的警告和提示",
    "No Hidden Dialogs Yet": "暂无隐藏的弹窗",
    "You haven't marked any dialogs as \"Don't ask again\". Any hidden dialogs will appear here to manage.": "您尚未将任何弹窗标记为“不再询问”。任何隐藏的弹窗都将显示在此处以供管理。",
    "You haven’t marked any dialogs as \"Don’t ask again\". Any hidden dialogs will appear here to manage.": "您尚未将任何弹窗标记为“不再询问”。任何隐藏的弹窗都将显示在此处以供管理。",

    // ── 下面原本误放入了短词字典 ──
    "Submit with ": "使用 ",
    "When enabled, ": "启用后，",
    " submits chat and ": " 提交聊天，",
    " inserts a newline": " 插入换行",
    "Accept the next word of a suggestion via ": "使用 ",
    " accept the next word of a suggestion": " 接受建议的下一个词",
    "Automatically import necessary modules for TypeScript": "自动为 TypeScript 导入必要的模块",

    // Codebase 相关设置
    "Codebase": "代码库",
    "Codebase Indexing": "代码库索引",
    "Delete Index": "删除索引",
    "Index New Folders": "索引新文件夹",
    "Automatically index any new folders with fewer than 10,000 files": "自动索引少于 10,000 个文件的新文件夹",
    "Automatically index any new folders with fewer than 250,000 files": "自动索引少于 250,000 个文件的新文件夹",
    "View included files.": "查看已包含的文件。",
    "Team-Level Repository Control": "团队级代码库控制",
    "Disable AI features in specific repositories based on file pattern": "基于文件匹配模式在特定代码库中禁用 AI 功能",
    "Index Repositories for Instant Grep": "为 Instant Grep 索引代码库",
    "Automatically index repositories to speed up Grep searches. All data is stored locally.": "自动索引代码库以加速 Grep 搜索。所有数据均存储在本地。",
    "Crawl and index custom resources and developer docs": "爬取并索引自定义资源和开发者文档",
    "No Docs Added": "未添加文档",
    "Add Doc": "添加文档",
    "Increase limits for faster responses": "提升额度以获取更快响应",
    "Automatically jump to the next diff when accepting changes with ": "当接受更改时，自动跳转到下一个差异，借助 ",
    "Ignore Files in ": "忽略包含在 ",
    "Ignore Files in .cursorignore": "忽略 .cursorignore 中的文件",
    "Nightly Updates Apply Automatically": "每夜更新自动应用",
    "Copy Domains": "复制域名",
    "Run Diagnostic": "运行诊断",
    "Learn about codebase indexing": "了解代码库索引",
    "Embed codebase for improved contextual understanding and knowledge. Embeddings and metadata are stored in the": "嵌入代码库以增强上下文理解和知识。嵌入向量和元数据存储在",
    ", but all code is stored locally.": "，但所有代码都存储在本地。",
    "Agent Review": "智能体审查",
    "Data Sharing is controlled by ": "数据共享由",
    "team admin.": "团队管理员控制。",
    "Nightly builds will silently download and install updates without prompting you.": "每夜版本将静默下载并安装更新，不会提示您。",
    "Keybinding: editor.action.inlineSuggest.acceptNextWord": "快捷键: editor.action.inlineSuggest.acceptNextWord",
    "Keybinding: ": "快捷键: ",
    "Keybinding:": "快捷键:",
    "Check recent git history": "检查最近 Git 历史",
    "Check current git status": "检查当前 Git 状态",
    "recent git history": "最近 Git 历史",
    "current git status": "当前 Git 状态",
    "New Agents Window": "新建 Agents Window",
    "Developer: New Additional Agents Window": "开发者：新建额外 Agents Window",
    "Switch to Agents Window": "切换到 Agents Window",
    "Open or Focus Agents Window": "打开或聚焦 Agents Window",
    "Meet the new Agents Window": "认识全新的 Agents Window",
    "Jump back to the Agents Window to keep working across repos.": "返回 Agents Window，继续跨代码库工作。",
    "Run many agents in parallel — across repos, locally, on remote SSH, and in the cloud.": "在不同代码库、本地、远程 SSH 和云端并行运行多个智能体。",
    "Try it now": "立即体验",
    "New Empty Editor Window": "新建空编辑器窗口",
    "Open or Focus Editor Window": "打开或聚焦编辑器窗口",
    "Open or focus the editor (IDE) window from the Agents window.": "从 Agents Window 打开或聚焦编辑器（IDE）窗口。",
    "Open Glass and Change to Multitask": "打开 Agents Window 并切换到多任务",
    "Opens or focuses the Glass window, then selects Multitask mode there.": "打开或聚焦 Agents Window，并在其中选择多任务模式。",
    "Parallelize Build with Multitask Mode.": "使用多任务模式并行构建。",
    "Coordinate parallel tasks...": "协调并行任务...",
    "Upgrade to Ultra Plan for near unlimited use, or set a Spend Limit for overages.": "升级到 Ultra 套餐以获得近乎无限的使用量，或设置超额消费限额。",
    "Open Editor Window": "打开编辑器窗口",
    "Open in Editor Window": "在编辑器窗口中打开",
    "Open in New Window": "在新窗口中打开",
    "Import from Editor Window": "从编辑器窗口导入",
    "Open New Agent Chat": "打开新智能体聊天",
    "New Agent in Project": "在项目中新建智能体",
    "New Agent with Model": "使用模型新建智能体",
    "New Agent with Query": "使用查询新建智能体",
    "New Agent with Context": "使用上下文新建智能体",
    "New Agent (preserve editor panel)": "新建智能体（保留编辑器面板）",
    "Failed to start multitasking.": "启动多任务失败。",
    "Starting Multitask": "正在启动多任务",
    "Start Multitasking": "启动多任务",
    "Run tasks in parallel": "并行运行任务",
    "New project": "新建项目",
    "Open project": "打开项目",
    "Clone repo": "克隆仓库",
    "Connect via SSH": "通过 SSH 连接",
    "Connect via WSL": "通过 WSL 连接",
    "New Window": "新窗口",
    "Recent projects": "最近项目",
    "View all": "查看全部",
    "Try a new window for running parallel agents": "尝试使用新窗口运行并行智能体",
    "Open project: ": "打开项目：",

    // ── Agent 欢迎页 ──
    "Start with a plan": "从计划开始",
    "Align on implementation before writing code": "在编写代码前先明确实现方案",
    "Debug an issue": "调试问题",
    "Find root causes and fix tricky bugs": "定位根因并修复棘手问题",
    "Create a dashboard": "创建仪表板",
    "Visualize information in a custom interface": "在自定义界面中可视化信息",

    // ── Automations ──
    "Automate repetitive tasks with always-on cloud agents that respond to environment triggers.": "使用始终在线的云端智能体自动执行由环境触发的重复任务。",
    "Automate repetitive tasks with always-on agents and configure Cursor's built-in agents for your team.": "使用始终在线的智能体自动执行重复任务，并为团队配置 Cursor 内置智能体。",
    "Automations use Cloud Agents, which require us to give agents access to your codebase. This is not compatible with Legacy Privacy Mode.": "自动化功能使用云端智能体，需要授予智能体访问代码库的权限。这与旧版隐私模式不兼容。",
    "Edit Privacy Settings": "编辑隐私设置",
    "Learn More": "了解更多",

    // ── Agent 面板、标签页菜单与搜索弹窗 ──
    "New Agent": "新建智能体",
    "Code Block Word Wrap": "代码块自动换行",
    "Wrap long lines in Agent conversation code blocks": "在智能体对话代码块中自动换行长行",
    "Voice Submit Keywords": "语音提交关键词",
    "Custom words that submit a voice prompt. Spaces and punctuation are ignored.": "用于提交语音提示的自定义词。会忽略空格和标点。",
    "Custom words that submit a voice prompt.": "用于提交语音提示的自定义词。",
    "Spaces and punctuation are ignored.": "会忽略空格和标点。",
    "Task Models": "任务模型",
    "Explore Subagent Model": "探索子智能体模型",
    "Choose the model used by the Explore subagent for initial research": "选择探索子智能体进行初始研究时使用的模型",
    "Choose the model used by Explore subagent for initial research": "选择探索子智能体进行初始研究时使用的模型",
    "Deployment Name": "部署名称",
    "AWS Bedrock": "AWS Bedrock",
    "Configure AWS Bedrock to use Anthropic Claude models through your AWS account.": "配置 AWS Bedrock，通过你的 AWS 账号使用 Anthropic Claude 模型。",
    "Cursor Enterprise teams can configure IAM roles to access Bedrock without any Access Keys.": "Cursor 企业团队可以配置 IAM 角色，无需访问密钥即可访问 Bedrock。",
    "Your team has configured AWS Bedrock access. You can use your teams Bedrock instance without any additional configuration.": "你的团队已配置 AWS Bedrock 访问权限。无需额外配置即可使用团队的 Bedrock 实例。",
    "Access Key ID": "访问密钥 ID",
    "Secret Access Key": "秘密访问密钥",
    "Test Model": "测试模型",
    "AWS Access Key ID": "AWS 访问密钥 ID",
    "AWS Secret Access Key": "AWS 秘密访问密钥",
    "Ignore Files": "忽略文件",
    "Hierarchical Cursor Ignore": "分层 Cursor 忽略",
    "Ignore Symlinks in Cursor Ignore Search": "在 Cursor 忽略搜索中忽略符号链接",
    "Toggle Chat Pane": "切换聊天面板",
    "Maximize Chat": "最大化聊天",
    "Close Tab": "关闭标签页",
    "Close Other Tabs": "关闭其他标签页",
    "Close All Tabs": "关闭所有标签页",
    "Open Tab as Editor": "在编辑器中打开标签页",
    "Export Transcript": "导出对话记录",
    "Copy Request ID": "复制请求 ID",
    "Agent Settings": "智能体设置",
    "Search Agents...": "搜索智能体...",
    "Search Agents…": "搜索智能体…",
    "No matching agents": "未找到匹配的智能体",
    "Archived": "已归档",
    "Open in Web": "在网页中打开",
    "Copy Transcript": "复制对话记录",
    "Copy Web Link": "复制网页链接",
    "Copy Deep Link": "复制深层链接",
    "Copy Branch": "复制分支",

    // ── Glass 外观设置 ──
    "Follow System Color Scheme": "跟随系统配色方案",
    "Match the active theme to your OS dark/light setting": "根据操作系统的深色/浅色设置匹配当前主题",
    "Light Theme": "浅色主题",
    "Choose the theme used when your system is in light mode": "选择系统处于浅色模式时使用的主题",
    "Dark Theme": "深色主题",
    "Choose the theme used when your system is in dark mode": "选择系统处于深色模式时使用的主题",
    "Manage Themes": "管理主题",
    "Manage Themes...": "管理主题...",
    "Create your own themes, tweak the vibe, and import your favorites": "创建自己的主题、调整风格并导入喜欢的主题",
    "Toggle between Light/Dark Themes": "切换浅色/深色主题",
    "Motion": "动态效果",
    "Reduce Motion": "减少动态效果",
    "Minimize interface animations": "减少界面动画",
    "Minimize interface animations. System follows your OS preference.": "减少界面动画。系统会跟随您的操作系统偏好。",

    // ── IDE 界面 ──
    "Switch Agent Mode": "切换 Agent 模式",
    "Toggle Agents": "切换 Agents",
    "Toggle Agents Side Bar": "切换 Agents 侧边栏",
    "Open Cursor Settings": "打开 Cursor 设置",
    "Give Feedback": "提供反馈",
    "Conversation Density": "对话密度",
    "Choose how much detail Agent tool calls show in the conversation": "选择 Agent 工具调用在对话中显示多少细节",
    "Agent Window": "Agent 窗口",
    "Last Used Windows": "上次使用的窗口",
    "Play a sound when agents finish or need attention": "智能体完成或需要关注时播放提示音",
    "All commands will run without approval, classification or sandboxing.": "所有命令将无需审批、分类或沙箱化即可直接运行",
    "Terminal and Editing": "终端与编辑",
    "Open Local Links in Cursor Browser": "在 Cursor 浏览器中打开本地链接",

    // ── 聊天与智能体 ──
    "Fork Chat": "分叉聊天",
    "Fork chat": "分叉聊天",
    "Forking chat": "正在分叉聊天",
    "Open in New Tab": "在新标签页中打开",
    "Mark as Unread": "标记为未读",
    "Archive Prior Chats": "归档之前的聊天",
    "Archive all chats older than this one": "归档早于当前聊天的所有聊天",
    "Show Console": "显示控制台",
    "Hide Console": "隐藏控制台",

    // ── 浏览器工具 ──
    "Take Screenshot": "截图",
    "Capture Area Screenshot": "区域截图",
    "Hard Reload": "硬刷新",
    "Copy Current URL": "复制当前 URL",
    "Clear Browsing History": "清除浏览历史",
    "Clear Cookies": "清除 Cookie",
    "Clear Cache": "清除缓存",
    "Select element": "选择元素",
    "Enter URL or search...": "输入 URL 或搜索...",
    "Enter a URL above, or instruct the Agent to navigate and use the browser": "在上方输入 URL，或指导 Agent 导航并使用浏览器",
    "This will remove all browsing history entries.": "这将删除所有浏览历史记录",
    "This will remove all cookies. You may be signed out of websites.": "这将删除所有 Cookie，您可能会被退出网站",
    "This will clear the browser cache.": "这将清除浏览器缓存",

    // ── 短词（已核实全部为 UI 显示，无键盘表/枚举冲突）──
    "Edit": "编辑",
    "Pin": "固定",
    "Unpin": "取消固定",
    "Zoom": "缩放",
    "Compact": "紧凑",
    "Balanced": "平衡",
    "Detailed": "详细",

    // ── Agent 窗口菜单 ──
    "Shortcuts": "快捷键",
    "Contact Us": "联系我们",
    "Move to": "移动到",
    "Archive": "归档",
    "Restore": "恢复",
    "Automate repetitive tasks with always-on cloud agents that respond to environment triggers.": "自动化重复性任务：常驻云端智能体响应环境触发器",
    "Automations use Cloud Agents, which require us to give agents access to your codebase. This is not compatible with Legacy Privacy Mode.": "自动化使用云端智能体，这需要我们允许智能体访问您的代码库。这与旧版隐私模式不兼容",
    "Edit Privacy Settings": "编辑隐私设置",
    "View License": "查看许可证",
    "Command Palette": "命令面板",
    "Reset Zoom": "重置缩放",
    "Zoom In": "放大",
    "Zoom Out": "缩小",
    "New Terminal": "新建终端",
    "New Browser Tab": "新建浏览器标签页",
    "Open IDE": "打开 IDE",
    "Exit": "退出",

    // ── 设置页：主题、LSP、工作树 ──
    "Cursor Settings": "Cursor 设置",
    "You can also do this later in Cursor Settings.": "您也可以稍后在 Cursor 设置中执行此操作。",
    "Select All": "全选",
    "New Browser": "新建浏览器",
    "Show rotating tips on the empty screen.": "在空屏幕上显示轮播提示。",
    "Agent Conversations": "智能体对话",
    "Tool Call Density": "工具调用密度",
    "Adjust how much detail is shown for tool calls": "调整工具调用显示的详细程度",
    "Select Theme...": "选择主题...",
    "Following System Color Scheme": "跟随系统配色方案",
    "Sync Theme with IDE": "与 IDE 同步主题",
    "Keep theme and follow-system settings matched with the IDE window": "保持主题和跟随系统设置与 IDE 窗口匹配",
    "Follow System High Contrast": "跟随系统高对比度",
    "Switch to a high contrast theme when your OS is in a high contrast mode": "当操作系统处于高对比度模式时切换到高对比度主题",
    "High Contrast Light Theme": "高对比度浅色主题",
    "Choose the theme used when your system is in light high contrast mode": "选择系统处于浅色高对比度模式时使用的主题",
    "High Contrast Dark Theme": "高对比度深色主题",
    "Choose the theme used when your system is in dark high contrast mode": "选择系统处于深色高对比度模式时使用的主题",
    "Enabled by Run Everything Auto-Run Mode: Agent bypasses approval prompts for tools including Web Search.": "已由「运行一切」自动运行模式启用：Agent 对包括网络搜索在内的工具绕过审批提示。",
    "Max Worktrees": "最大工作树数量",
    "Max Total Size (GB)": "最大总大小（GB）",
    "Cursor-Managed Worktrees": "Cursor 托管的工作树",
    "Report Issue": "报告问题",
    "Toggle Developer Tools": "切换开发者工具",
    "Open Process Explorer": "打开进程资源管理器",
    "Show Chat History": "显示聊天历史",
    "Switch Model": "切换模型",
    "Add files, folders, docs...": "添加文件、文件夹、文档...",
    "Code Intelligence": "代码智能",
    "Enable LSPs": "启用 LSP",
    "Enable LSPs for Worktrees": "为工作树启用 LSP",
    "Maximum Local LSP Workspaces": "本地 LSP 工作区上限",
    "Maximum Remote LSP Workspaces": "远程 LSP 工作区上限",
    "Enable language server by default to provide code intelligence in workspaces": "默认启用语言服务器以在工作区提供代码智能",
    "Enable language server by default to provide code intelligence in agent worktree workspaces": "默认启用语言服务器以在 Agent 工作树工作区提供代码智能",
    "Maximum local workspaces that can run language servers at the same time": "可同时运行语言服务器的本地工作区数量上限",
    "Maximum remote workspaces that can run language servers at the same time": "可同时运行语言服务器的远程工作区数量上限",

    // ── 用量页 / 插件市场 / 团队 MCP / 侧边栏 ──
    "Discover": "发现",
    "Cursor Models": "Cursor 模型",
    "Other Models": "其他模型",
    "Consumed by named models.": "由命名的模型消耗。",
    "Additional usage beyond limits consumes Other Models quota or on-demand spend.": "超出限额的额外用量会消耗其他模型配额或按需计费。",
    "Show everything from all sources": "显示所有来源的全部内容",
    "Cursor Marketplace": "Cursor 插件市场",
    "Official plugins from our partners": "来自我们合作伙伴的官方插件",
    "Add Marketplace": "添加插件市场",
    "Import Marketplace": "导入插件市场",
    "Import or create a plugin marketplace": "导入或创建插件市场",
    "Open Web Links in Cursor Browser": "在 Cursor 浏览器中打开网页链接",
    "Automatically open http and https links in the Browser Tab": "在浏览器标签页中自动打开 http 和 https 链接",
    "Show Apps": "显示应用",
    "Hide Apps": "隐藏应用",
    "Configured in the dashboard": "在控制台中配置",
    "Configure MCP servers in the dashboard to make them available in Cursor on desktop and in the cloud.": "在控制台中配置 MCP 服务器，使其在桌面端和云端的 Cursor 中可用。",
    "Configure Team MCP Servers": "配置团队 MCP 服务器",
    "Show Sidebar": "显示侧边栏",
    "Hide Sidebar": "隐藏侧边栏",
    "Collapse Sidebar": "折叠侧边栏",
    "Add Symbol to Current Chat": "添加符号到当前聊天",
    "Add Symbol to New Chat": "添加符号到新聊天",

    // ── VS Code 常用设置描述（描述来自 nls.messages.json，经 y() 加载）──
    "Controls the font size in pixels.": "控制字体大小（像素）。",
    "Controls the font family.": "控制字体家族。",
    "Controls the font family of the inline suggestions.": "控制行内建议的字体家族。",
    "Enables/Disables font ligatures ('calt' and 'liga' font features). Change this to a string for fine-grained control of the 'font-feature-settings' CSS property.": "启用/禁用字体连字（'calt' 和 'liga' 字体特性）。可改为字符串以精细控制 'font-feature-settings' CSS 属性。",
    "Controls the font weight. Accepts \"normal\" and \"bold\" keywords or numbers between 1 and 1000.": "控制字体粗细。接受 \"normal\" 和 \"bold\" 关键字或 1 到 1000 之间的数字。",
    "Controls the letter spacing in pixels.": "控制字符间距（像素）。",
    "The number of spaces a tab is equal to. This setting is overridden based on the file contents when {0} is on.": "一个制表符等于的空格数。当 {0} 开启时，该设置会基于文件内容被覆盖。",
    "Insert spaces when pressing `Tab`. This setting is overridden based on the file contents when {0} is on.": "按下 `Tab` 时插入空格。当 {0} 开启时，该设置会基于文件内容被覆盖。",
    "Controls how lines should wrap.": "控制行的换行方式。",
    "Controls the wrapping column of the editor when `#editor.wordWrap#` is `wordWrapColumn` or `bounded`.": "当 `#editor.wordWrap#` 为 `wordWrapColumn` 或 `bounded` 时，控制编辑器的换行列。",
    "Controls the display of line numbers.": "控制行号的显示。",
    "Controls whether the smooth caret animation should be enabled.": "控制是否启用平滑光标动画。",
    "Controls the cursor style in insert input mode.": "控制插入输入模式下的光标样式。",
    "Controls the width of the cursor when `#editor.cursorStyle#` is set to `line`.": "当 `#editor.cursorStyle#` 设置为 `line` 时，控制光标的宽度。",
    "Controls the width of the cursor when {0} is set to {1}.": "当 {0} 设置为 {1} 时，控制光标的宽度。",
    "Controls if format on save formats the whole file or only modifications. Only applies when `#editor.formatOnSave#` is enabled.": "控制保存时格式化是格式化整个文件还是仅格式化修改部分。仅在 `#editor.formatOnSave#` 启用时生效。",
    "Controls how the editor should render whitespace characters.": "控制编辑器如何渲染空白字符。",
    "Controls how the editor should render the current line highlight.": "控制编辑器如何渲染当前行高亮。",
    "Controls whether bracket pair colorization is enabled or not. Use {0} to override the bracket highlight colors.": "控制是否启用括号对着色。使用 {0} 覆盖括号高亮颜色。",
    "Enables tab completions.": "启用 Tab 补全。",
    "Controls whether the editor should automatically close brackets after the user adds an opening bracket.": "控制编辑器是否在用户输入左括号后自动闭合括号。",
    "Controls whether the editor should automatically adjust the indentation when users type, paste, move or indent lines.": "控制编辑器在用户输入、粘贴、移动或缩进行时是否自动调整缩进。",
    "Controls whether the editor should automatically surround selections when typing quotes or brackets.": "控制编辑器在输入引号或括号时是否自动包围所选内容。",
    "Controls whether the editor shows CodeLens.": "控制编辑器是否显示 CodeLens。",
    "Controls whether the editor will scroll beyond the last line.": "控制编辑器是否允许滚动超过最后一行。",
    "Controls whether selections should have rounded corners.": "控制选区是否使用圆角。",
    "Controls whether the editor has linked editing enabled. Depending on the language, related symbols such as HTML tags, are updated while editing.": "控制是否启用关联编辑。编辑时，相关符号（如 HTML 标签）会随语言一同更新。",
    "Controls how suggestions are pre-selected when showing the suggest list.": "控制显示建议列表时建议的预选方式。",
    "Controls whether a border should be drawn around the overview ruler.": "控制是否在概览标尺周围绘制边框。",
    "Defines a default formatter which takes precedence over all other formatter settings. Must be the identifier of an extension contributing a formatter.": "定义默认格式化器，优先级高于所有其他格式化设置。必须是提供格式化器的扩展标识符。",
    "Controls whether the minimap is shown.": "控制是否显示缩略图。",
    "Limit the width of the minimap to render at most a certain number of columns.": "限制缩略图的宽度，最多渲染指定数量的列。",
    "Render the actual characters on a line as opposed to color blocks.": "渲染行中的实际字符，而非颜色块。",
    "Controls whether bracket pair guides are enabled or not.": "控制是否启用括号对指引线。",
    "Remove trailing auto inserted whitespace.": "移除自动插入的尾随空白。",
    "Controls whether to automatically show inline suggestions in the editor.": "控制是否在编辑器中自动显示行内建议。",
    "Enables a pop-up that shows parameter documentation and type information as you type.": "启用弹出窗口，在您输入时显示参数文档和类型信息。",
    "Special handling for large files to disable certain memory intensive features.": "针对大文件的特殊处理，以禁用某些内存密集型功能。",
    "Shows the nested current scopes during the scroll at the top of the editor.": "在编辑器顶部滚动时显示嵌套的当前作用域。",
    "Controls whether the semanticHighlighting is shown for the languages that support it.": "控制是否对支持的语言显示语义高亮。",
    "Controls whether the cursor should jump to find matches while typing.": "控制输入时光标是否跳转到查找匹配项。",
    "Controls whether the editor should render indent guides.": "控制编辑器是否渲染缩进指引线。",
    "Controls whether the hover is shown.": "控制是否显示悬停提示。",
    "Characters that will be used as word separators when doing word related navigations or operations.": "执行与单词相关的导航或操作时，用作单词分隔符的字符。",
    "Controls whether the editor should automatically close quotes after the user adds an opening quote.": "控制编辑器是否在用户输入左引号后自动闭合引号。",
    "Controls whether the editor should allow moving selections via drag and drop.": "控制编辑器是否允许通过拖放移动选区。",
    "Controls whether syntax highlighting should be copied into the clipboard.": "控制复制到剪贴板时是否包含语法高亮。",
    "Controls whether copying without a selection copies the current line.": "控制无选区时复制是否复制当前行。",
    "The modifier to be used to add multiple cursors with the mouse. The Go to Definition and Open Link mouse gestures will adapt such that they do not conflict with the [multicursor modifier](https://code.visualstudio.com/docs/editor/codebasics#_multicursor-modifier).": "用于通过鼠标添加多个光标的修饰键。转到定义和打开链接的鼠标手势会相应调整，避免与此[多光标修饰键](https://code.visualstudio.com/docs/editor/codebasics#_multicursor-modifier)冲突。",
    "Controls the font size in pixels of the terminal.": "控制终端的字体大小（像素）。",
    "Controls the line height of the terminal. This number is multiplied by the terminal font size to get the actual line-height in pixels.": "控制终端的行高。该数字乘以终端字体大小得到实际行高（像素）。",
    "Controls the letter spacing of the terminal. This is an integer value which represents the number of additional pixels to add between characters.": "控制终端的字符间距。该整数值表示字符之间额外增加的像素数。",
    "Controls whether the terminal cursor blinks.": "控制终端光标是否闪烁。",
    "Controls the style of terminal cursor when the terminal is focused.": "控制终端获得焦点时光标的样式。",
    "Controls the style of terminal cursor when the terminal is not focused.": "控制终端失去焦点时光标的样式。",
    "Controls the maximum number of lines the terminal keeps in its buffer. We pre-allocate memory based on this value in order to ensure a smooth experience. As such, as the value increases, so will the amount of memory.": "控制终端在缓冲区中保留的最大行数。我们会根据此值预分配内存以确保流畅体验，因此该值越大，占用的内存越多。",
    "Controls where newly created terminals will appear.": "控制新创建的终端出现的位置。",
    "Controls the font family of the terminal. Defaults to {0}'s value.": "控制终端的字体家族。默认使用 {0} 的值。",
    "The default character set encoding to use when reading and writing files. This setting can also be configured per language.": "读写文件时使用的默认字符集编码。也可按语言配置。",
    "The default end of line character.": "默认的行尾字符。",
    "When enabled, will trim trailing whitespace when saving a file.": "启用后，保存文件时会修剪尾随空白。",
    "When enabled, insert a final new line at the end of the file when saving it.": "启用后，保存文件时会在文件末尾插入一个最终换行符。",
    "When enabled, will trim all new lines after the final new line at the end of the file when saving it.": "启用后，保存文件时会修剪最终换行符之后的所有换行符。",
    "Controls whether preview mode is used when editors open. There is a maximum of one preview mode editor per editor group. This editor displays its filename in italics on its tab or title label and in the Open Editors view. Its contents will be replaced by the next editor opened in preview mode. Making a change in a preview mode editor will persist it, as will a double-click on its label, or the 'Keep Open' option in its label context menu. Opening a file from Explorer with a double-click persists its editor immediately.": "控制编辑器打开时是否使用预览模式。每个编辑器组最多有一个预览模式编辑器。该编辑器会在标签页、标题标签和打开的编辑器视图中以斜体显示文件名。其内容会被下一个以预览模式打开的编辑器替换。在预览模式编辑器中做出更改会使其固定，双击其标签或选择标签上下文菜单中的『保持打开』也同样会固定。在资源管理器中双击文件会立即固定其编辑器。",
    "Controls which editor is shown at startup, if none are restored from the previous session.": "控制启动时显示哪个编辑器（如果未从上一会话恢复任何编辑器）。",
    "Controls the location of the primary side bar and activity bar. They can either show on the left or right of the workbench. The secondary side bar will show on the opposite side of the workbench.": "控制主侧边栏和活动栏的位置。它们可以显示在工作台的左侧或右侧。辅助侧边栏显示在工作台的另一侧。",
    "Controls the visibility of the status bar at the bottom of the suggest widget.": "控制建议小部件底部状态栏的可见性。",
    "Controls the visibility of the status bar at the bottom of the workbench.": "控制工作台底部状态栏的可见性。",
    "Controls whether opened editors should show as individual tabs, one single large tab or if the title area should not be shown.": "控制打开的编辑器是显示为独立标签页、单个大标签页，还是不显示标题区域。",
    "Controls the format of the label for an editor.": "控制编辑器标签的格式。",
    "Controls whether the last typed input to the command palette should be restored when opening it the next time.": "控制下次打开命令面板时是否恢复上次输入的内容。",
    "Controls how windows and editors within are being restored when opening.": "控制打开时如何恢复窗口及其中的编辑器。",
    "Specifies the color theme used in the workbench when {0} is not enabled.": "指定 {0} 未启用时工作台使用的颜色主题。",
    "Specifies the file icon theme used in the workbench or 'null' to not show any file icons.": "指定工作台使用的文件图标主题，或使用 'null' 不显示任何文件图标。",
    "Controls the location of the Activity Bar relative to the Primary and Secondary Side Bars.": "控制活动栏相对于主侧边栏和辅助侧边栏的位置。",
    "Controls the size of editor tabs. This value is ignored when {0} is not set to {1}.": "控制编辑器标签页的大小。当 {0} 未设置为 {1} 时，此值会被忽略。",
    "Controls the window title based on the current context such as the opened workspace or active editor. Variables are substituted based on the context:": "根据当前上下文（如打开的工作区或活动编辑器）控制窗口标题。变量根据上下文替换：",
    "When enabled, the diff editor ignores changes in leading or trailing whitespace.": "启用后，差异编辑器会忽略行首或行尾空白的变化。",
    "Controls whether the diff editor shows the diff side by side or inline.": "控制差异编辑器是并排还是内联显示差异。",
    "Controls the line height in pixels in the Debug Console. Use 0 to compute the line height from the font size.": "控制调试控制台的行高（像素）。使用 0 根据字体大小计算行高。",
    "Zoom the font of the editor when using mouse wheel and holding `Cmd`.": "按住 `Cmd` 使用鼠标滚轮时缩放编辑器字体。",
    "Zoom the font of the editor when using mouse wheel and holding `Ctrl`.": "按住 `Ctrl` 使用鼠标滚轮时缩放编辑器字体。",
    "Controls whether the editor should render control characters.": "控制编辑器是否渲染控制字符。",
    "Detect Indentation from Content": "根据内容检测缩进",
    "Always show the folding controls.": "始终显示折叠控件。",
    "Print the path to a terminal shell integration script. Allowed values are 'bash', 'pwsh', 'zsh' or 'fish'.": "打印终端 shell 集成脚本的路径。允许的值为 'bash'、'pwsh'、'zsh' 或 'fish'。",
    "Controls the line height. \n - Use 0 to automatically compute the line height from the font size.\n - Values between 0 and 8 will be used as a multiplier with the font size.\n - Values greater than or equal to 8 will be used as effective values.": "控制行高。\n - 使用 0 根据字体大小自动计算行高。\n - 0 到 8 之间的值将作为字体大小的乘数。\n - 大于或等于 8 的值将作为实际值使用。",
    "Format a file on save. A formatter must be available and the editor must not be shutting down. When {0} is set to `afterDelay`, the file will only be formatted when saved explicitly.": "保存时格式化文件。必须有可用的格式化器，且编辑器不能正在关闭。当 {0} 设置为 `afterDelay` 时，仅在显式保存时格式化文件。",

    // ── Cursor 设置分区（VS Code 设置里的 Cursor 分区）──
    "Run Private Inference in a separate local process to isolate it from remote workspace activity. Reload Cursor after changing this setting.": "在独立的本地进程中运行私有推断，以将其与远程工作区活动隔离。更改此设置后请重新加载 Cursor。",
    "When Cursor closes while an agent is working, pick the agent back up the next time you open Cursor.": "当 Cursor 在智能体工作时关闭，下次打开 Cursor 时继续该智能体的工作。",
    "Show Projects as Agents across the app. When off, the UI reads Projects.": "在应用中把项目显示为智能体。关闭后，界面显示为项目。",
    "Show side chats, Canvases, and Desktop as sections in the supplemental sidebar": "在辅助侧边栏中将侧边聊天、画布和桌面显示为分区",
    "Show a colored card behind expanded sections in the supplemental sidebar": "在辅助侧边栏中展开的分区后面显示彩色卡片",
    "Keep the supplemental sidebar visible as an icon rail when collapsed": "折叠时保持辅助侧边栏以图标栏形式可见",
    "Collapse the supplemental sidebar to its icon rail after a sidebar item opens or focuses a tab": "侧边栏项打开或聚焦标签页后，将辅助侧边栏折叠为图标栏",
    "Use one set of open sidebar sections for every agent. When off, each agent remembers its own open sections until the window closes": "为每个智能体使用同一组打开的侧边栏分区。关闭后，每个智能体会记住自己打开的分区，直到窗口关闭",
    "Where new agents start by default": "新智能体默认启动的位置",
    "Sync chats and continue them in Cursor": "同步聊天并在 Cursor 中继续",
    "Sign in to get started with Cursor's AI features": "登录以开始使用 Cursor 的 AI 功能",
    "The plugins you're removing from the marketplace will no longer be available to users and Cloud Agents that rely on them.": "您从插件市场移除的插件将不再对依赖它们的用户和云端智能体可用。",
    "Plugins bundle rules, skills, subagents, commands, MCP servers, and hooks into one installable package.": "插件将规则、技能、子智能体、命令、MCP 服务器和钩子打包到一个可安装的包中。",
    "Model Context Protocol servers connect Cursor to external tools and data sources like Linear, Figma, and Notion.": "模型上下文协议（MCP）服务器将 Cursor 连接到外部工具和数据源，如 Linear、Figma 和 Notion。",
    "Skills package domain-specific knowledge and workflows that Agent applies automatically when relevant.": "技能打包了领域特定知识和工作流，智能体会在相关时自动应用。",
    "Subagents are specialized assistants that run in their own context window so Agent can parallelize and stay focused.": "子智能体是在自己的上下文窗口中运行的专业助手，让智能体可以并行处理并保持专注。",
    "Rules give Agent persistent, system-level instructions for your coding standards and workflows.": "规则为智能体提供关于编码标准和工作流的持久化系统级指令。",
    "Hooks run custom scripts at lifecycle events to observe, control, and extend the agent loop.": "钩子在生命周期事件中运行自定义脚本，以观察、控制和扩展智能体的运行循环。",
    "Choose which source configures this MCP server.": "选择配置此 MCP 服务器的来源。",
    "Let Cursor see logs and view your app with Playwright MCP": "让 Cursor 通过 Playwright MCP 查看日志和应用",
    "Enable browser tools": "启用浏览器工具",
    "Configuration for MCP (Model Control Protocol) servers": "MCP（模型上下文协议）服务器的配置",
    "Command to start the stdio-based MCP server": "启动基于 stdio 的 MCP 服务器的命令",
    "URL of the SSE-based MCP server": "基于 SSE 的 MCP 服务器的 URL",
    "Creates a new MCP configuration with example servers": "使用示例服务器创建新的 MCP 配置",
    "Define a new skill for the agent to use": "为智能体定义一个新技能",
    "Add Symbol to Current Chat...": "添加符号到当前聊天...",
    "Add Symbol to New Chat...": "添加符号到新聊天...",
    "Create a cursor rule from the highlighted text": "从选中的文本创建 Cursor 规则",
    "Orchestrate multiple subagents in parallel": "并行编排多个子智能体",
    "Create an agent to start working on tasks": "创建智能体开始处理任务",
    "Reset auto format on agent finish override": "重置智能体完成时自动格式化的覆盖设置",
    "Disable Cursor Tab for these languages": "为这些语言禁用 Cursor Tab",
    "Enable partial accepts for Cursor Tab, using the editor.action.inlineSuggest.acceptNextWord keybinding": "为 Cursor Tab 启用部分接受，使用 editor.action.inlineSuggest.acceptNextWord 键绑定",
    "Show notification toasts in the same location as the chat": "在与聊天相同的位置显示通知提示",
    "Interval in hours for periodic worktree cleanup. Default is 6 hours.": "定期清理工作树的间隔（小时）。默认为 6 小时。",
    "Maximum number of local Agent Window workspaces that can run language servers.": "可运行语言服务器的本地 Agent 窗口工作区数量上限。",
    "Maximum number of remote Agent Window workspaces that can run language servers.": "可运行语言服务器的远程 Agent 窗口工作区数量上限。",
    "Maximum total size in GB for the Cursor worktrees directory across all workspaces. Set to 0 to disable this limit.": "所有工作区中 Cursor 工作树目录的最大总大小（GB）。设置为 0 可禁用此限制。",
    "Enable Cmd+P / Ctrl+P shortcut for file picker in Composer": "在 Composer 中启用 Cmd+P / Ctrl+P 文件选择器快捷键",
    "Model to use for subagent tasks": "子智能体任务使用的模型",
    "Automatically save files in normal composers": "在普通 Composer 中自动保存文件",
    "Play a sound when a chat response is completed": "聊天响应完成时播放提示音",
    "Path to a custom sound file (mp3, wav, ogg) to play when Agent finishes responding. Leave empty to use the default sound.": "智能体完成响应时播放的自定义声音文件（mp3、wav、ogg）路径。留空使用默认声音。",
    "Wrap long lines in Agent chat code blocks.": "在 Agent 聊天代码块中自动换行。",
    "Adjust the default behavior of sending a message while Agent is streaming": "调整 Agent 输出时发送消息的默认行为",
    "Controls the text size scale (relative to base 12px) of AI chat messages.": "控制 AI 聊天消息的文本大小比例（相对于基础 12px）。",
    "Controls how shell and edit-file tool calls are displayed and grouped in Glass Agent conversations.": "控制 Glass Agent 对话中 shell 和编辑文件工具调用的显示和分组方式。",
    "Controls how shell and edit-file tool calls are displayed and grouped in Editor Agent conversations.": "控制编辑器 Agent 对话中 shell 和编辑文件工具调用的显示和分组方式。",
    "Controls the maximum width in pixels of chat content.": "控制聊天内容的最大宽度（像素）。",
    "When to display the usage summary at the bottom of the chat pane: automatically when approaching limits, always, or never.": "何时在聊天面板底部显示用量摘要：接近限额时自动显示、始终显示或从不显示。",
    "Suggest a follow-up after each turn; Tab to insert": "每轮对话后建议后续问题；按 Tab 插入",
    "Semantic Search Highlight": "语义搜索高亮",
    "Work with Cloud Agents from Slack": "通过 Slack 使用云端智能体",
    "Configure browser automation": "配置浏览器自动化",
    "Select your preferred embedding model. Delete your index and reload to use it.": "选择偏好的嵌入模型。删除索引并重新加载后生效。",
    "Control tokens control how likely the model is to produce no-ops. Will be replaced with auto-selection": "控制令牌控制模型产生无操作的概率。将替换为自动选择",
    "What model new agents use by default": "新智能体默认使用的模型",
    "Allow agents on this machine to be controlled remotely from mobile and web": "允许从手机和网页远程控制此机器上的智能体",
    "You can configure Shell, MCP and Fetch allowlists for Auto mode. However, Auto works well without these.": "您可以为自动模式配置 Shell、MCP 和 Fetch 允许列表。不过，自动模式没有这些也能正常工作。",
    "Automatically run Review when Agent finishes and has made file changes": "智能体完成并修改文件后自动运行 Review",
    "Sign in to load cloud user and team MCP servers from the dashboard and manage which servers are enabled for cloud agents.": "登录以从控制台加载云用户和团队的 MCP 服务器，并管理哪些服务器对云端智能体启用。",
    "Add a custom MCP tool in your user MCP config or configure workspace-specific tools in <project-root>/.cursor/mcp.json.": "在用户 MCP 配置中添加自定义 MCP 工具，或在 <project-root>/.cursor/mcp.json 中配置工作区特定工具。",
    "Add a custom MCP tool in your Home MCP config.": "在 Home MCP 配置中添加自定义 MCP 工具。",
    "Add MCP tools to <project-root>/.cursor/mcp.json in this workspace.": "在此工作区的 <project-root>/.cursor/mcp.json 中添加 MCP 工具。",
    "OpenAI-compatible API base URL for the local agent.": "本地智能体的 OpenAI 兼容 API 基础 URL。",
    "Personal usage for your primary enterprise team.": "您的主企业团队的个人用量。",
    "Unlock 3x more usage on Agent & more": "解锁 Agent 等 3 倍更多用量",
    "Enable on-demand usage to go beyond your plan's included usage. Requires a paid plan.": "启用按需用量以超出套餐包含的用量。需要付费套餐。",
    "Show Cursor in the menu bar": "在菜单栏显示 Cursor",
    "Show Cursor in the system tray": "在系统托盘显示 Cursor",
    "Allow the agent to celebrate with a shower of confetti": "允许智能体用彩带庆祝",
    "Set a fixed amount or make on-demand usage unlimited": "设置固定金额或让按需用量无限制",
    "Allow Agent to switch modes without asking first": "允许 Agent 无需询问即可切换模式",
    "Automatically format files when Agent finishes": "智能体完成时自动格式化文件",
    "Show Add to Chat and Quick Edit buttons": "显示添加到聊天和快速编辑按钮",

    // ── 截图排查补充 ──
    "Show rotating tips on the empty screen": "在空屏幕上显示轮播提示",
    "Learn more about Agent Review": "了解 Agent Review 的更多信息",
    "Automatically parse links pasted into Quick Edit": "粘贴到快速编辑时自动解析链接",

    // ── nls 原生菜单缺失词条（带 visibility 后缀的完整形式）──
    "Show Agents Side Bar": "显示 Agents 侧边栏",
    "Agents Window Button": "Agents Window 按钮",
    "Open Agents Window": "打开 Agents Window",
    "Toggle Agents Side Bar visibility": "切换 Agents 侧边栏可见性",
    "Toggle Agents visibility": "切换 Agents 可见性",
    "Open Agents Window and Start Cloud Agent": "打开 Agents Window 并启动云端智能体",
    "All Agents": "全部智能体",
    "Run Many Agents in Parallel": "并行运行多个智能体",

    // ── 用户反馈的未翻译词条补充 ──
    "From Marketplace": "从插件市场",
    "From Local Repo": "从本地仓库",
    "Create Reusable Commands": "创建可复用命令",
    "Commands are reusable prompts you invoke with /name to standardize common workflows across your team.": "命令是可复用的提示，您可以通过 /name 调用，以标准化团队中的常见工作流。",
    "Hooks that run during the agent's loop will show up here.": "在智能体循环中运行的钩子将显示在此处。",
    "Include Third-Party Plugins, Skills, and Other Configs": "包含第三方插件、技能和其他配置",
    "Run Cursor anywhere...": "在任何地方运行 Cursor...",
    "Click or hold Ctrl M to dictate": "点击或按住 Ctrl M 进行听写",
    "New Worktree": "新建工作树",
    "Give Feedback...": "提供反馈...",
    "Toggle Primary Side Bar": "切换主侧边栏",
    "User Config": "用户配置",
    "Add Folder": "添加文件夹",
    "Clear log": "清空日志",
    "Recents": "最近",
    "This PC": "此电脑",
    "+ Add": "+ 添加",
    "Run on": "运行于",
    "Documentation": "文档",

    // ── 用户反馈第二批未翻译词条 ──
    "Show Terminal": "显示终端",
    "Hide Terminal": "隐藏终端",
    "Toggle Developer Tools": "切换开发者工具",
    "Open Process Explorer": "打开进程浏览器",
    "Toggle Agents": "切换智能体",
    "Toggle Agents Side Bar": "切换智能体侧边栏",
    "Show Agents Side Bar": "显示智能体侧边栏",
    "Open Cursor Settings": "打开 Cursor 设置",
    "Open config": "打开配置",
    "Disable": "禁用",
    "Systematically diagnose and fix bugs using runtime traces": "使用运行时跟踪系统性地诊断和修复 Bug",
    "Automatically import necessary modules for TypeScript": "自动为 TypeScript 导入必要模块",
    "Thinking intensity": "思考强度",
    "Refresh model list": "刷新模型列表",
    "Add or search model": "添加或搜索模型",
    "Generate an implementation plan": "生成实施计划",
    "Pinpoint the root cause of an issue": "定位问题的根本原因",
    "Answer questions without making edits": "回答问题而不进行编辑",
    "Plan changes": "规划变更",
    "Debug issues": "调试问题",
    "Ask questions": "提问",
    "Search agents, files, actions...": "搜索智能体、文件、操作...",
    "Search Cursor settings\\u2026": "搜索 Cursor 设置…",
    "Customize Sidebar": "自定义侧边栏",
    "Recent Agents": "最近使用的智能体",
    "Recent Files": "最近打开的文件",
    "Recent Actions": "最近操作",
    "Recent Workspaces": "最近工作区",
    "Recently Viewed": "最近查看",
    "Change Filter": "切换筛选器",
    "Last Used": "上次使用",
    "New Worktree": "新工作树",
    "Go Back": "返回",
    "Go Forward": "前进",
    "Open Workspace": "打开工作区",
    "Cursor Local": "Cursor 本地",
};

// 原生工作台菜单与加载状态来自 nls.messages.json。它们是短词，不能加入
// safeGlobalDict，否则可能改变 bundle 中的协议值或键位数据。
const nativeNlsDict = {
    "File": "文件",
    "Edit": "编辑",
    "Selection": "选择",
    "View": "视图",
    "Go": "转到",
    "Run": "运行",
    "Terminal": "终端",
    "Help": "帮助",
    "Default": "默认",
    "Loading...": "正在加载...",
    "Exit": "退出",
    "Changes": "更改",
    "Zoom In": "放大",
    "Zoom Out": "缩小",
    "Reset Zoom": "重置缩放",
    "Archive": "归档",
    "Command Palette": "命令面板",
    "View License": "查看许可证",
    "New Terminal": "新建终端",
    "Configure Icon Visibility": "配置图标可见性",
    "Undo": "撤销",
    "Redo": "重做",
    "Cut": "剪切",
    "Copy": "复制",
    "Paste": "粘贴",
    "Select All": "全选",
    "Enabled": "已启用",
    "Report Issue": "报告问题",
    "Open": "打开",
    "Add Repository": "添加代码库",
    "Image": "图片",
    "Disable": "禁用",
    "Show": "显示",
    "Hide": "隐藏",
    "Import": "导入",
    "Small": "小",
    "Large": "大",
    // ── 用户反馈缺失：nls 索引词条（ft()/E() 从 nls.messages.json 取值）──
    "Collapse All": "全部折叠",
    "Show Details": "显示详情",
    "Hide Details": "隐藏详情",
    "Ask Agent": "询问智能体",
    "Discard Changes": "放弃更改",
    "Discard All Changes": "放弃所有更改",
    "Home": "主页",

    // ── 标题栏/视图/面板名称 ──
    "Primary Side Bar": "主侧边栏",
    "Secondary Side Bar": "辅助侧边栏",
    "Panel": "面板",
    "Agents Side Bar": "智能体侧边栏",
    "Agents Window": "智能体窗口",
    "Process Explorer": "进程浏览器",
    "Developer Tools": "开发者工具",
    "Toggle Primary Side Bar Position": "切换主侧边栏位置",
    "Toggle Primary Side Bar Visibility": "切换主侧边栏可见性",
    "Move Primary Side Bar Right": "将主侧边栏移到右侧",
    "Move Primary Side Bar Left": "将主侧边栏移到左侧",
    "Hide Primary Side Bar": "隐藏主侧边栏",
    "Toggle Secondary Side Bar Visibility": "切换辅助侧边栏可见性",
    "Hide Secondary Side Bar": "隐藏辅助侧边栏",
    "Toggle Panel Visibility": "切换面板可见性",
    "Hide Panel": "隐藏面板",
    "Open Cursor Settings": "打开 Cursor 设置",
    "Cursor Settings": "Cursor 设置",
    "Workspace Process Explorer": "工作区进程浏览器",
    "Open Workspace Process Explorer": "打开工作区进程浏览器",
    "Toggle Panel": "切换面板",

    // ── NLS 模板 ──
    "Show {0}": "显示 {0}",
    "Toggle {0}": "切换 {0}",
    "Hide {0}": "隐藏 {0}",

    // ── 带 && 的菜单条目（无 && 的纯净文本） ──
    "Give Feedback...": "提供反馈...",

    // ── 补充 NLS 短词（riskyShortWords 仅处理 JS 中的 UI 属性，此处补全 nls.messages.json）──
    "Search": "搜索",
    "Suggested": "推荐",
    "Go Back": "返回",
    "Go Forward": "前进",
    "Open Workspace": "打开工作区",
    "Current workspace: {0}": "当前工作区：{0}",
    "Find": "查找",
    "Replace": "替换",
    "Recent": "最近",
    // ── 快速打开（Ctrl+P）──
    "Search files, content, and symbols (append {0} to go to line or {1} to go to symbol)": "搜索文件、内容和符号（追加 {0} 跳转到行，{1} 跳转到符号）",
    "Go to File...": "转到文件...",
    "Go to File": "转到文件",
    // ── 命令面板命令描述 ──
    "Switch between recently used agents": "在最近使用的智能体间切换",
    "Search chat history": "搜索聊天记录",
    // ── 开发者/调试命令（NLS key → 中文）──
    "Start File Watch Recording": "开始文件监视记录",
    "Open Developer Tools for Extension Host": "打开扩展宿主的开发者工具",
    "Start Extension Host CPU Profiler": "启动扩展宿主 CPU 分析器",
    "Start Extension Host Heap Allocation Profiler": "启动扩展宿主堆分配分析器",
    "Start Remote Server CPU Profiler": "启动远程服务器 CPU 分析器",
    "Open Process Explorer": "打开进程资源管理器",
    "Start Electron Trace": "开始 Electron 跟踪",
    "Capture and Send Debugging Data": "捕获并发送调试数据",
    "Developer": "开发者",
    "Delete Old Chats...": "删除旧聊天...",
};

const riskyShortWords = {
    "General": "通用",
    "Appearance": "外观",
    "Back": "返回",
    "VS Code Settings": "VS Code 设置",
    "Plan & Usage": "套餐与用量",
    "Current Plan": "当前套餐",
    "Agents": "智能体",
    "Conversation": "对话",
    // "Tab" 不可放入危险短词：workbench 键盘扫描表为 [n,n,"Tab",n,"Tab",n,"VK_TAB"]，
    // jsxRegex 会误匹配 49,"Tab" 导致 KeybindingService cannot be dispatched。
    // 设置页侧栏 Tab 项由 i18n-core.js scopedReplacements 的 tab:"Tab" 单独处理。
    "Models": "模型",
    "Plugins": "插件",
    "Hooks": "钩子",
    "Network": "网络",
    "Beta": "测试功能",
    "Indexing": "索引",
    "Marketplace": "插件市场",
    "Manage View": "管理视图",
    "Group By": "分组方式",
    "Sort By": "排序方式",
    "All": "全部",
    "User": "用户",
    "Search": "搜索",
    "Theme": "主题",
    "Automations": "自动化",
    "System": "系统",
    "Colors": "颜色",
    "Hue": "色相",
    "Intensity": "强度",
    "Chat": "聊天",
    "Agent": "智能体",
    "Editor": "编辑器",
    "Triage": "分诊",
    "Spec": "规格",
    "Project": "项目",
    "Typography": "字体排版",
    "Worktrees": "工作树",
    "Cleanup": "清理",
    "Subagents": "子智能体",
    "Git": "Git",
    "Docs": "官方文档",
    "Open": "打开",
    "Invite": "邀请",
    "Import": "导入",
    "Show": "显示",
    "Auto-Run": "自动运行",
    "Pane": "面板",
    "On": "开启",
    "Small": "小",
    "Default": "默认",
    "Large": "大",
    "Imports": "导入",
    "Rules": "规则",
    "Skills": "技能",
    "Subagents": "子智能体",
    "Commands": "命令",
    "Unlimited": "无限制",
    "Disabled": "已禁用",
    "Fixed": "固定",
    "Total": "总计",
    "Custom": "自定义",
    "Auto": "自动",
    "Always": "始终",
    "Never": "从不",
    "Ran": "已运行",
    "Quick": "快速",
    "Deep": "深度",
    "Context": "上下文",
    "Motion": "动态效果",
    "Reduce Motion": "减少动态效果",
    "Light Theme": "浅色主题",
    "Dark Theme": "深色主题",
    "Manage Themes": "管理主题",
    "Follow System Color Scheme": "跟随系统配色方案",
    "Log Out": "退出登录",
    "Open Folder": "打开文件夹",
    "Browse Marketplace": "浏览插件市场",
    "Suggested": "推荐",
    "Copy Domains": "复制域名",
    "Run Diagnostic": "运行诊断",
    "Development": "开发",
    "Early Access": "抢先体验",
    "Nightly": "每夜构建",
    "Configured Hooks": "已配置的钩子",
    "Execution Log": "执行日志",
    "Clear log": "清空日志",
    "Tools": "工具",
    "Browser": "浏览器",
    "Installed MCP Servers": "已安装的 MCP 服务器",
    "Off": "关闭",
    "Browser Tab": "浏览器标签页",
    "Copy Command": "复制命令",
    "Checkout": "检出",
    "View Report": "查看报告",
    "Pasted Link": "已粘贴链接",
    "Remote HTTPS": "远程 HTTPS",
    "Command": "命令",
    "Arguments": "参数",
    "Secrets": "密钥",
    "Server URL": "服务器 URL",
    "HTTP headers": "HTTP 请求头",
    "Client ID": "客户端 ID",
    "Client Secret": "客户端密钥",
    "Team Access": "团队访问权限",
    "All Members": "所有成员",
    "Configure": "配置",
    "Remove": "移除",
    "Plugin": "插件",
    "MCP Server": "MCP 服务器",
    "Default Off": "默认关闭",
    "Default On": "默认开启",
    "Required": "必需",
    "Uninstall": "卸载",
    "Add to Team": "添加到团队",
    "Imported": "已导入",
    "Local": "本地",
    "Recent": "最近",
    "Agents": "智能体",
    "Extension": "扩展",
    "Verified": "已验证",
    "Pinned": "已固定",
    "Previous": "上一个",
    "Next": "下一个",
    "Scopes": "作用域",
    "Options": "选项",
    "Moving...": "正在移动...",
    "Complete": "完成",
    "Failed": "失败",
    "View plan": "查看计划",
    "Mine": "我的",
    "Shared": "共享",
    "Copy Code": "复制代码",
    "Copy link": "复制链接",
    "Open link": "打开链接",
    "Copy table": "复制表格",
    "Zoom in": "放大",
    "Zoom out": "缩小",
    "Show Code": "显示代码",
    "Copy Error": "复制错误",
    "Run History": "运行历史",
    "No Runs Yet": "暂无运行记录",
    "Cancel": "取消",
    "Confirm": "确认",
    "Done": "完成",
    "Editor Window": "编辑器窗口",
    "Plan New Idea": "规划新想法",
    "Cursor Local": "Cursor 本地",
    "Hide": "隐藏",
    "Edit": "编辑",
    "Manage": "管理",
    "Save": "保存",
    "Cut": "剪切",
    "Copy": "复制",
    "Paste": "粘贴",
    "Export": "导出",
    "Fork": "分叉",
    "Pin": "固定",
    "Unpin": "取消固定",
    "Rename": "重命名",
    "Archive": "归档",
    "Discard": "丢弃",
    "Share": "分享",

    // 常见词/键名：代码中存在枚举值或键盘扫描表，必须走短词保护机制
    "Add": "添加",
    "Clear": "清除",
    "Delete": "删除",
    "File": "文件",
    "View": "视图",
    "Terminal": "终端",
    "Changes": "更改",
    "Help": "帮助",
    "Undo": "撤销",
    "Redo": "重做",
    "Select": "选择",
    "Select All": "全选",
    "Tips": "提示",
    "Status": "状态",
    "Scope": "作用域",
    "Enabled": "已启用",
    "Light": "浅色",
    "Dark": "深色",
    "Light High Contrast": "浅色高对比度",
    "Dark High Contrast": "深色高对比度",
    "High Contrast": "高对比度",
    "Cursor Light": "Cursor 浅色",
    "Cursor Dark": "Cursor 深色",
    "Cursor Light Colorblind (Beta)": "Cursor 浅色色盲（Beta）",
    "Cursor Dark High Contrast": "Cursor 深色高对比度",
    "Connected": "已连接",
    "Installed": "已安装",
    "Image": "图片",
    "Cloud": "云端",
    "Copy Path": "复制路径",
    "Copy Relative Path": "复制相对路径",
    "Search Files": "搜索文件",
    "Set Log Level...": "设置日志级别..."
};

module.exports = { safeGlobalDict, nativeNlsDict, riskyShortWords };
